// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockRedstoneTorch extends BlockTorch {
	// FIELDS
	private boolean torchActive;
	private static java.util.List torchUpdates;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract void a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract int b();
	
	/**
	 * 
	 */
	public abstract void b(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract boolean b(IBlockAccess a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract boolean c();
	
	/**
	 * 
	 */
	public abstract boolean d(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void e(World a, int b, int c, int d);

}
