// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockFire extends Block {
	// FIELDS
	private int[] chanceToEncourageFire;
	private int[] abilityToCatchFire;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1796_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1806_a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1799_a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1797_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1798_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1807_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1804_b(IBlockAccess a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1803_d();
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_1795_d(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1808_e(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1805_f(World a, int b, int c, int d, int e);

}
