// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockPumpkin extends Block {
	// FIELDS
	private boolean field_4086;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a);
	
	/**
	 * 
	 */
	public abstract boolean a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void a(World a, int b, int c, int d, EntityLiving e);
	
	/**
	 * 
	 */
	public abstract void e(World a, int b, int c, int d);

}
