// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockFlower{
	// FIELDS
	public int a;
	public int b;
	public int c;
	public int d;
	public int e;
	public NoiseGenerator2 f;
	public IMobs g;
	
	// METHODS

}
