// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockFlowing extends BlockFluids {
	// FIELDS
	 int field_659;
	 boolean[] field_658;
	 int[] field_660;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract void e(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	protected abstract int e(World a, int b, int c, int d, int e);

}
