// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockPumpkin extends Block {
	// FIELDS
	private boolean field_4086;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_382_a(int a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_384_a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_385_a(World a, int b, int c, int d, EntityLiving e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_383_e(World a, int b, int c, int d);

}
