// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockMinecartTrack extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_103_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_106_a(World a, int b, int c, int d);
	
	/**
	 * Ray traces through the blocks collision from start vector to end vector returning a ray trace hit. Args: world, x, y, z, startVec, endVec
	 */
	public abstract MovingObjectPosition collisionRayTrace(World a, int b, int c, int d, Vec3D e, Vec3D f);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_105_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_104_a(IBlockAccess a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_108_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_102_d(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_107_e(World a, int b, int c, int d);

}
