// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockJukeBox extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_933_a(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_936_a(World a, int b, int c, int d, int e, float f);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_934_a(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_935_f(World a, int b, int c, int d, int e);

}
