// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockIce extends BlockBreakable {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1960_a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1959_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1957_a(IBlockAccess a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1958_b(World a, int b, int c, int d);

}
