// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockChest extends BlockContainer{
	// FIELDS
	private java.util.Random a;
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d, EntityPlayer e)
	
	/**
	 * 
	 */
	private boolean g(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public int a(int a)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	protected TileEntity a_()

}
