// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockMobSpawner extends BlockContainer{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public int a(int a, java.util.Random b)
	
	/**
	 * 
	 */
	public int a(java.util.Random a)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	protected TileEntity a_()

}
