// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockRedstoneOre extends Block {
	// FIELDS
	private boolean field_665;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_253_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_250_a(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_252_a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_254_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_247_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_249_b(World a, int b, int c, int d, Entity e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_248_b(World a, int b, int c, int d, EntityPlayer e);

}
