// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockSnowBlock extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, java.util.Random e)
	
	/**
	 * 
	 */
	public int a(int a, java.util.Random b)
	
	/**
	 * 
	 */
	public int a(java.util.Random a)

}
