// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockBreakable extends Block {
	// FIELDS
	private boolean field_6084;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1526_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1527_a(IBlockAccess a, int b, int c, int d, int e);

}
