// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockChest extends BlockContainer {
	// FIELDS
	private java.util.Random field_656;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a);
	
	/**
	 * 
	 */
	public abstract boolean a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract boolean a(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	protected abstract TileEntity a_();
	
	/**
	 * 
	 */
	public abstract void b(World a, int b, int c, int d);

}
