// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockStep extends Block {
	// FIELDS
	private boolean a;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1853_a();
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1852_a(int a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1856_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1857_a(IBlockAccess a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1854_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1855_e(World a, int b, int c, int d);

}
