// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockSign extends BlockContainer {
	// FIELDS
	private java.lang.Class field_654;
	private boolean field_653;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_504_a();
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_506_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_503_a(IBlockAccess a, int b, int c, int d);
	
	/**
	 * 
	 */
	protected abstract TileEntity MIDDLECRAFT_func_505_a_();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_507_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_502_d(World a, int b, int c, int d);

}
