// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockContainer extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	protected abstract TileEntity a_();
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public void e(World a, int b, int c, int d);

}
