// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockMushroom extends BlockFlower{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean f(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	protected boolean b(int a)

}
