// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockBookshelf extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_589_a(int a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_590_a(java.util.Random a);

}
