// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockLog extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a);
	
	/**
	 * 
	 */
	public abstract int a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract int a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract void b(World a, int b, int c, int d);

}
