// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockRedstoneOre extends Block {
	// FIELDS
	private boolean field_665;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract boolean a(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	public abstract void a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract int a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract int b();
	
	/**
	 * 
	 */
	public abstract void b(World a, int b, int c, int d, Entity e);
	
	/**
	 * 
	 */
	public abstract void b(World a, int b, int c, int d, EntityPlayer e);

}
