// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockFurnace extends BlockContainer {
	// FIELDS
	private boolean field_655;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a);
	
	/**
	 * 
	 */
	public abstract int a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract boolean a(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	public abstract void a(World a, int b, int c, int d, EntityLiving e);
	
	/**
	 * 
	 */
	protected abstract TileEntity a_();
	
	/**
	 * 
	 */
	public abstract void e(World a, int b, int c, int d);

}
