// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Block {
	// FIELDS
	public static Block waterStill;
	public static Block waterMoving;
	public static Block lavaStill;
	public static Block lavaMoving;
	public static Block sand;
	public static Block gravel;
	public static Block oreGold;
	public static Block oreIron;
	public static Block oreCoal;
	public static Block wood;
	public static BlockLeaves leaves;
	public static Block sponge;
	public static Block glass;
	public static Block field_9042;
	public static Block field_9041;
	public static Block field_9040;
	public static Block field_9039;
	public static Block field_9038;
	public static Block field_9037;
	public static Block field_9036;
	public static Block field_9034;
	public static Block field_9033;
	public static Block field_9032;
	public static Block field_9031;
	public static Block field_9030;
	public static Block field_9029;
	private java.lang.String field_666;
	public static Block tilledField;
	public static Block stoneOvenIdle;
	public static Block stoneOvenActive;
	public static Block signPost;
	public static Block doorWood;
	public static Block ladder;
	public static Block minecartTrack;
	public static Block stairCompactCobblestone;
	public static Block signWall;
	public static Block lever;
	public static Block pressurePlateStone;
	public static Block doorSteel;
	public static Block pressurePlatePlanks;
	public static Block oreRedstone;
	public static Block oreRedstoneGlowing;
	public static Block torchRedstoneIdle;
	public static Block torchRedstoneActive;
	public static Block button;
	public static Block snow;
	public static Block ice;
	public static Block blockSnow;
	public static Block cactus;
	public static Block blockClay;
	public static Block reed;
	public static Block jukebox;
	public static Block fence;
	public static Block field_9049;
	public static Block cloth;
	public static Block field_9048;
	public static BlockFlower plantYellow;
	public static BlockFlower plantRed;
	public static BlockFlower mushroomBrown;
	public static BlockFlower mushroomRed;
	public static Block blockGold;
	public static Block blockSteel;
	public static Block stairDouble;
	public static Block stairSingle;
	public static Block brick;
	public static Block tnt;
	public static Block bookShelf;
	public static Block cobblestoneMossy;
	public static Block obsidian;
	public static Block torchWood;
	public static BlockFire fire;
	public static Block mobSpawner;
	public static Block stairCompactPlanks;
	public static Block crate;
	public static Block redstoneWire;
	public static Block oreDiamond;
	public static Block blockDiamond;
	public static Block workbench;
	public static Block crops;
	public static Block pumpkin;
	public static Block bloodStone;
	public static Block slowSand;
	public static Block lightStone;
	public static BlockPortal portal;
	public static Block pumpkinLantern;
	public int blockIndexInTexture;
	public int blockID;
	protected float blockHardness;
	protected float blockResistance;
	public double minX;
	public double minY;
	public double minZ;
	public double maxX;
	public double maxY;
	public double maxZ;
	public StepSound stepSound;
	public float field_554;
	public Material blockMaterial;
	public float slipperiness;
	public static StepSound soundPowderFootstep;
	public static StepSound soundWoodFootstep;
	public static StepSound soundGravelFootstep;
	public static StepSound soundGrassFootstep;
	public static StepSound soundStoneFootstep;
	public static StepSound soundMetalFootstep;
	public static StepSound soundGlassFootstep;
	public static StepSound soundClothFootstep;
	public static StepSound soundSandFootstep;
	public static Block[] blocksList;
	public static boolean[] tickOnLoad;
	public static boolean[] opaqueCubeLookup;
	public static boolean[] isBlockContainer;
	public static int[] lightOpacity;
	public static boolean[] unusedBooleanArray;
	public static int[] lightValue;
	public static Block stone;
	public static BlockGrass grass;
	public static Block dirt;
	public static Block cobblestone;
	public static Block planks;
	public static Block sapling;
	public static Block bedrock;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_549_a();
	
	/**
	 * Sets the amount of light emitted by a block from 0.0f to 1.0f (converts internally to 0-15). Returns the object for convenience in constructing.
	 */
	protected abstract Block setLightValue(float a);
	
	/**
	 * Sets the bounds of the block.  minX, minY, minZ, maxX, maxY, maxZ
	 */
	public abstract void setBlockBounds(float a, float b, float c, float d, float e, float f);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_546_a(int a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_559_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_550_a(int a, boolean b);
	
	/**
	 * Sets the footstep sound for the block. Returns the object for convenience in constructing.
	 */
	protected abstract Block setStepSound(StepSound a);
	
	/**
	 * 
	 */
	public abstract float MIDDLECRAFT_func_562_a(Entity a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_565_a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_553_a(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_561_a(World a, int b, int c, int d, int e, float f);
	
	/**
	 * 
	 */
	public abstract MovingObjectPosition MIDDLECRAFT_func_563_a(World a, int b, int c, int d, Vec3D e, Vec3D f);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_547_a(World a, int b, int c, int d, AxisAlignedBB e, java.util.ArrayList f);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_574_a(World a, int b, int c, int d, Entity e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_570_a(World a, int b, int c, int d, Entity e, Vec3D f);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_566_a(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_552_a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_577_a(World a, int b, int c, int d, EntityLiving e);
	
	/**
	 * *
	 */
	public abstract float func_254(EntityPlayer a);
	
	/**
	 * *
	 */
	public abstract Block func_20037(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_558_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_571_a(IBlockAccess a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_545_a(IBlockAccess a, int b, int c, int d, int e);
	
	/**
	 * Sets whether this block type will tick on loading the block or not
	 */
	protected abstract void setTickOnLoad(boolean a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_560_a_(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_555_b();
	
	/**
	 * Sets the the blocks resistance to explosions. Returns the object for convenience in constructing.
	 */
	protected abstract Block setResistance(float a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_557_b(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_554_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_567_b(World a, int b, int c, int d, Entity e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_569_b(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_572_b(IBlockAccess a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_573_c();
	
	/**
	 * Sets how many hits it takes to break a block.
	 */
	protected abstract Block setHardness(float a);
	
	/**
	 * Sets how much light is blocked going through this block. Returns the object for convenience in constructing.
	 */
	protected abstract Block setLightOpacity(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_564_c(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_568_c(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_551_d();
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_548_d(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_575_d(World a, int b, int c, int d, int e);
	
	/**
	 * *
	 */
	public abstract java.lang.String func_20036();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_556_e(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_576_f(World a, int b, int c, int d);
	
	/**
	 * *
	 */
	public abstract void harvestBlock(World a, int b, int c, int d, int e);

}
