// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockSnow extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1535_a();
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1540_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1536_a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1542_a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1541_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1543_a(IBlockAccess a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1537_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_1534_d(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1539_g(World a, int b, int c, int d, int e);

}
