// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockOre extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_810_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_811_a(java.util.Random a);

}
