// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockTNT extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a);
	
	/**
	 * 
	 */
	public abstract void a(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract int a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract void b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void c(World a, int b, int c, int d);

}
