// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockTNT extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_103_a(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_107_a(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_105_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_104_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_106_c(World a, int b, int c, int d);

}
