// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockReed extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a();
	
	/**
	 * 
	 */
	public int a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public AxisAlignedBB d(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public boolean f(World a, int b, int c, int d);
	
	/**
	 * *
	 */
	 void func_4037(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	protected final void g(World a, int b, int c, int d);

}
