// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockTorch extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_642_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_643_a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract MovingObjectPosition MIDDLECRAFT_func_648_a(World a, int b, int c, int d, Vec3D e, Vec3D f);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_645_a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_647_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_644_c(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_641_d(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_646_e(World a, int b, int c, int d);

}
