// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockLog extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1300_a(int a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1298_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1297_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1299_b(World a, int b, int c, int d);

}
