// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockGrass extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1529_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1528_a(World a, int b, int c, int d, java.util.Random e);

}
