// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockPumpkin extends Block{
	// FIELDS
	private boolean a;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public int a(int a);
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, EntityLiving e);
	
	/**
	 * 
	 */
	public void e(World a, int b, int c, int d);

}
