// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockLeavesBase extends Block {
	// FIELDS
	protected boolean graphicsLevel;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1007_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1008_a(IBlockAccess a, int b, int c, int d, int e);

}
