// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockLightStone extends javax.swing.JComponent{
	// FIELDS
	private int[] a;
	private int b;
	private java.lang.String[] c;
	
	// METHODS
	
	/**
	 * 
	 */
	private void a()
	
	/**
	 * 
	 */
	static void a(BlockLightStone a)
	
	/**
	 * 
	 */
	public void paint(java.awt.Graphics a)

}
