// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockSoil extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, java.util.Random e)
	
	/**
	 * 
	 */
	private boolean h(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public AxisAlignedBB d(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	private boolean g(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public int a(int a, java.util.Random b)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, Entity e)

}
