// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockDoor extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d, EntityPlayer e)
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, boolean e)
	
	/**
	 * 
	 */
	public void b(int a)
	
	/**
	 * 
	 */
	public AxisAlignedBB d(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public int d(int a)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, EntityPlayer e)
	
	/**
	 * 
	 */
	public void a(IBlockAccess a, int b, int c, int d)
	
	/**
	 * 
	 */
	public int a(int a, java.util.Random b)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	public MovingObjectPosition a(World a, int b, int c, int d, Vec3D e, Vec3D f)

}
