// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockLeavesBase extends Block{
	// FIELDS
	protected boolean a;
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(IBlockAccess a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public boolean a()

}
