// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockJukeBox extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d, EntityPlayer e)
	
	/**
	 * 
	 */
	public int a(int a)
	
	/**
	 * 
	 */
	public void f(World a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, int e, float f)

}
