// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockRedstoneTorch extends BlockTorch {
	// FIELDS
	private boolean torchActive;
	private static java.util.List torchUpdates;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_431_a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_428_a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_423_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_425_b(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_429_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_426_b(IBlockAccess a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_432_c();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_430_d(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_424_e(World a, int b, int c, int d);

}
