// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockSnowBlock extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public abstract void a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract int a(java.util.Random a);

}
