// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockContainer extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	protected abstract TileEntity MIDDLECRAFT_func_537_a_();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_536_b(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_535_e(World a, int b, int c, int d);

}
