// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockSnow extends lc{
	// FIELDS
	private ItemTool a;
	protected IMobs aj;
	protected boolean ak;
	
	// METHODS
	
	/**
	 * Checks if the entity's current position is a valid location to spawn this entity.
	 */
	public boolean getCanSpawnHere()
	
	/**
	 * 
	 */
	protected float a(int a, int b, int c)
	
	/**
	 * 
	 */
	protected void a(IMobs a, float b)
	
	/**
	 * 
	 */
	protected void c()
	
	/**
	 * 
	 */
	protected IMobs k()

}
