// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockButton extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_155_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_156_a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_163_a(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_168_a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_161_a(IBlockAccess a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_154_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_164_b(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_159_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_162_b(World a, int b, int c, int d, EntityPlayer e);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_165_b(IBlockAccess a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_167_c();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_157_c(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_153_d(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_166_d(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_158_e(World a, int b, int c, int d);

}
