// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockFence extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, AxisAlignedBB e, java.util.ArrayList f)
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean a()

}
