// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockFluids extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	protected int g(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, Entity e, Vec3D f)
	
	/**
	 * 
	 */
	public int b()
	
	/**
	 * 
	 */
	public static float b(int a)
	
	/**
	 * 
	 */
	protected void h(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public int a(int a)
	
	/**
	 * 
	 */
	private void i(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	private Vec3D c(IBlockAccess a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	public void e(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, java.util.Random e)
	
	/**
	 * 
	 */
	public AxisAlignedBB d(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public int a(int a, java.util.Random b)
	
	/**
	 * 
	 */
	public boolean a(int a, boolean b)
	
	/**
	 * 
	 */
	public int a(java.util.Random a)
	
	/**
	 * 
	 */
	public boolean a(IBlockAccess a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	protected int b(IBlockAccess a, int b, int c, int d)

}
