// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockLadder extends Block {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_512_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_513_a(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_516_a(java.util.Random a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_515_b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_514_c(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_511_d(World a, int b, int c, int d);

}
