// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockFlower extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean f(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, java.util.Random e)
	
	/**
	 * 
	 */
	protected final void g(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public AxisAlignedBB d(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	protected boolean b(int a)
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean a()

}
