// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockSign{
	// FIELDS
	private transient cr[] a;
	private transient int b;
	private int c;
	private final float d;
	private transient volatile int e;
	
	// METHODS
	
	/**
	 * 
	 */
	private static int a(int a)
	
	/**
	 * 
	 */
	private static int a(int a, int b)
	
	/**
	 * 
	 */
	private void a(int a, long b, java.lang.Object c, int d)
	
	/**
	 * 
	 */
	public java.lang.Object a(long a)
	
	/**
	 * 
	 */
	public void a(long a, java.lang.Object b)
	
	/**
	 * 
	 */
	private void a(cr[] a)
	
	/**
	 * 
	 */
	private void b(int a)
	
	/**
	 * 
	 */
	public java.lang.Object b(long a)
	
	/**
	 * 
	 */
	final Packet34EntityTeleport c(long a)
	
	/**
	 * 
	 */
	static int d(long a)
	
	/**
	 * 
	 */
	private static int e(long a)

}
