// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockSign extends BlockContainer{
	// FIELDS
	private java.lang.Class a;
	private boolean b;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a();
	
	/**
	 * 
	 */
	public int a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public void a(IBlockAccess a, int b, int c, int d);
	
	/**
	 * 
	 */
	protected TileEntity a_();
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public AxisAlignedBB d(World a, int b, int c, int d);

}
