// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockLeaves extends BlockLeavesBase{
	// FIELDS
	 int[] b;
	private int c;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a();
	
	/**
	 * 
	 */
	public int a(int a, java.util.Random b);
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, java.util.Random e);
	
	/**
	 * 
	 */
	public int a(java.util.Random a);
	
	/**
	 * *
	 */
	 void func_316(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, Entity e);
	
	/**
	 * *
	 */
	 void func_6091(World a, int b, int c, int d);
	
	/**
	 * 
	 */
	private void g(World a, int b, int c, int d);

}
