// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class BlockButton extends Block{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d, EntityPlayer e)
	
	/**
	 * 
	 */
	public int b()
	
	/**
	 * 
	 */
	public void c(World a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, EntityPlayer e)
	
	/**
	 * 
	 */
	public void a(IBlockAccess a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean a(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean d(World a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	public boolean c()
	
	/**
	 * 
	 */
	public void e(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void a(World a, int b, int c, int d, java.util.Random e)
	
	/**
	 * 
	 */
	public AxisAlignedBB d(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	private boolean g(World a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(World a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public boolean b(IBlockAccess a, int b, int c, int d, int e)

}
