// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Chunk{
	// FIELDS
	public NibbleArray f;
	public NibbleArray g;
	public World d;
	public NibbleArray e;
	public byte[] b;
	public boolean c;
	public static boolean a;
	public boolean n;
	public boolean o;
	public java.util.Map l;
	public java.util.List[] m;
	public final int j;
	public final int k;
	public byte[] h;
	public int i;
	public long s;
	public boolean r;
	public boolean q;
	public boolean p;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(java.lang.Class a, AxisAlignedBB b, java.util.List c)
	
	/**
	 * 
	 */
	public int a(byte[] a, int b, int c, int d, int e, int f, int g, int h)
	
	/**
	 * 
	 */
	private void f(int a, int b, int c)
	
	/**
	 * 
	 */
	public java.util.Random a(long a)
	
	/**
	 * 
	 */
	private void c(int a, int b)
	
	/**
	 * 
	 */
	public void b(Entity a)
	
	/**
	 * 
	 */
	private void g(int a, int b, int c)
	
	/**
	 * 
	 */
	public void b(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public int b(int a, int b)
	
	/**
	 * 
	 */
	public void b()
	
	/**
	 * 
	 */
	public int a(EnumSkyBlock a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void e(int a, int b, int c)
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	public void a(Entity a, int b)
	
	/**
	 * 
	 */
	public void e()
	
	/**
	 * 
	 */
	public TileEntity d(int a, int b, int c)
	
	/**
	 * 
	 */
	public void a(TileEntity a)
	
	/**
	 * 
	 */
	public boolean a(boolean a)
	
	/**
	 * 
	 */
	public void c()
	
	/**
	 * 
	 */
	public int a(int a, int b, int c)
	
	/**
	 * 
	 */
	public void a(Entity a)
	
	/**
	 * 
	 */
	public boolean c(int a, int b, int c)
	
	/**
	 * 
	 */
	public void d()
	
	/**
	 * 
	 */
	public void a(Entity a, AxisAlignedBB b, java.util.List c)
	
	/**
	 * 
	 */
	public boolean a(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void a(EnumSkyBlock a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public boolean a(int a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public void f()
	
	/**
	 * 
	 */
	public int b(int a, int b, int c)
	
	/**
	 * 
	 */
	public void a(int a, int b, int c, TileEntity d)
	
	/**
	 * 
	 */
	public boolean a(int a, int b)
	
	/**
	 * 
	 */
	public int c(int a, int b, int c, int d)

}
