// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkProviderGenerate{
	// FIELDS
	 double[] f;
	 double[] g;
	 double[] d;
	 double[] e;
	public NoiseGeneratorOctaves b;
	public NoiseGeneratorOctaves c;
	public NoiseGeneratorOctaves a;
	private NoiseGeneratorOctaves n;
	private NoiseGeneratorOctaves o;
	private NoiseGeneratorOctaves l;
	private NoiseGeneratorOctaves m;
	private java.util.Random j;
	private NoiseGeneratorOctaves k;
	 double[] h;
	 int[][] i;
	private double[] w;
	private jq[] v;
	private MapGenBase u;
	private double[] t;
	private double[] s;
	private double[] r;
	private double[] q;
	private World p;
	
	// METHODS
	
	/**
	 * 
	 */
	private double[] a(double[] a, int b, int c, int d, int e, int f, int g)
	
	/**
	 * 
	 */
	public void a(int a, int b, byte[] c, jq[] d, double[] e)
	
	/**
	 * 
	 */
	public Chunk b(int a, int b)
	
	/**
	 * 
	 */
	public void a(int a, int b, byte[] c, jq[] d)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	public void a(IChunkProvider a, int b, int c)
	
	/**
	 * 
	 */
	public boolean a(boolean a, IProgressUpdate b)
	
	/**
	 * 
	 */
	public boolean b()
	
	/**
	 * 
	 */
	public boolean a(int a, int b)

}
