// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkCoordIntPair {
	// FIELDS
	public int chunkXPos;
	public int chunkZPos;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract double func_73(Entity a);
	
	/**
	 * *
	 */
	public abstract boolean lk_equals(java.lang.Object a);
	
	/**
	 * *
	 */
	public abstract int lk_hashCode();

}
