// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkProviderLoadOrGenerate{
	// FIELDS
	private kx[] f;
	private World g;
	private IChunkProvider d;
	private IChunkLoader e;
	 int b;
	private Chunk c;
	 int a;
	private Chunk h;
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(boolean a, IProgressUpdate b)
	
	/**
	 * 
	 */
	public Chunk b(int a, int b)
	
	/**
	 * 
	 */
	private void b(Chunk a)
	
	/**
	 * 
	 */
	public boolean b()
	
	/**
	 * 
	 */
	private Chunk c(int a, int b)
	
	/**
	 * 
	 */
	private void a(Chunk a)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	public boolean a(int a, int b)
	
	/**
	 * 
	 */
	public void a(IChunkProvider a, int b, int c)

}
