// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface interface ChunkCoordinates{
	// FIELDS
	
	// METHODS
	
	/**
	 * Returns the block ID at coords x,y,z
	 */
	public abstract int getBlockId(int a, int b, int c)
	
	/**
	 * Returns the block metadata at coords x,y,z
	 */
	public abstract int getBlockMetadata(int a, int b, int c)
	
	/**
	 * Returns the block's material.
	 */
	public abstract la getBlockMaterial(int a, int b, int c)
	
	/**
	 * Returns if the block at the specified coordinates allow attachment Args: x, y, z
	 */
	public abstract boolean doesBlockAllowAttachment(int a, int b, int c)

}
