// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkLoader {
	// FIELDS
	private java.io.File field_945;
	private boolean field_944;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_442_a();
	
	/**
	 * 
	 */
	public abstract Chunk MIDDLECRAFT_func_440_a(World a, int b, int c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_441_a(World a, Chunk b);
	
	/**
	 * *
	 */
	public abstract void func_663(Chunk a, World b, NBTTagCompound c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_443_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_444_b(World a, Chunk b);

}
