// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkLoader{
	// FIELDS
	private boolean b;
	private java.io.File a;
	
	// METHODS
	
	/**
	 * 
	 */
	public Chunk a(World a, int b, int c)
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	private java.io.File a(int a, int b)
	
	/**
	 * 
	 */
	public void b(World a, Chunk b)
	
	/**
	 * 
	 */
	public void a(World a, Chunk b)
	
	/**
	 * 
	 */
	public void a(Chunk a, World b, NBTTagCompound c)
	
	/**
	 * 
	 */
	public void b()
	
	/**
	 * 
	 */
	public static Chunk a(World a, NBTTagCompound b)

}
