// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkCoordIntPair{
	// FIELDS
	public int a;
	public int b;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * *
	 */
	 double func_73(Entity a);
	
	/**
	 * 
	 */
	public double a(Entity a);
	
	/**
	 * *
	 */
	 boolean lk_equals(java.lang.Object a);
	
	/**
	 * 
	 */
	public boolean equals(java.lang.Object a);
	
	/**
	 * *
	 */
	 int lk_hashCode();
	
	/**
	 * 
	 */
	public int hashCode();

}
