// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkProviderHell{
	// FIELDS
	public NoiseGeneratorOctaves a;
	public NoiseGeneratorOctaves b;
	 double[] c;
	 double[] d;
	 double[] e;
	 ()V setChunkModified;
	 double[] g;
	private java.util.Random h;
	private NoiseGeneratorOctaves i;
	private NoiseGeneratorOctaves j;
	private NoiseGeneratorOctaves k;
	private NoiseGeneratorOctaves l;
	private NoiseGeneratorOctaves m;
	private World n;
	private double[] o;
	private double[] p;
	private double[] q;
	private double[] r;
	private MapGenBase s;
	
	// METHODS
	
	/**
	 * *
	 */
	 double[] func_4060(double[] a, int b, int c, int d, int e, int f, int g);
	
	/**
	 * 
	 */
	public boolean a();
	
	/**
	 * 
	 */
	public boolean a(int a, int b);
	
	/**
	 * 
	 */
	public void a(int a, int b, byte[] c);
	
	/**
	 * 
	 */
	public void a(IChunkProvider a, int b, int c);
	
	/**
	 * 
	 */
	public boolean a(boolean a, IProgressUpdate b);
	
	/**
	 * 
	 */
	private double[] a(double[] a, int b, int c, int d, int e, int f, int g);
	
	/**
	 * *
	 */
	 void func_4061(int a, int b, byte[] c);
	
	/**
	 * 
	 */
	public boolean b();
	
	/**
	 * 
	 */
	public Chunk b(int a, int b);
	
	/**
	 * 
	 */
	public void b(int a, int b, byte[] c);

}
