// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkCoordIntPair {
	// FIELDS
	public int chunkXPos;
	public int chunkZPos;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_1927_a(Entity a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1926_equals(java.lang.Object a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1925_hashCode();

}
