// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkProviderHell {
	// FIELDS
	public NoiseGeneratorOctaves field_4248;
	public NoiseGeneratorOctaves field_4247;
	 double[] field_4246;
	 double[] field_4245;
	 double[] field_4244;
	 double[] field_4243;
	 double[] field_4242;
	private java.util.Random field_4241;
	private NoiseGeneratorOctaves field_4240;
	private NoiseGeneratorOctaves field_4239;
	private NoiseGeneratorOctaves field_4238;
	private NoiseGeneratorOctaves field_4237;
	private NoiseGeneratorOctaves field_4236;
	private World field_4235;
	private double[] field_4234;
	private double[] field_4233;
	private double[] field_4232;
	private double[] field_4231;
	private MapGenBase field_4230;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_388_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_385_a(int a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_381_a(int a, int b, byte[] c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_386_a(IChunkProvider a, int b, int c);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_387_a(boolean a, IProgressUpdate b);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_389_b();
	
	/**
	 * 
	 */
	public abstract Chunk MIDDLECRAFT_func_383_b(int a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_382_b(int a, int b, byte[] c);

}
