// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ChunkProviderServer {
	// FIELDS
	private java.util.Set field_725;
	private Chunk field_724;
	private IChunkProvider field_730;
	private IChunkLoader field_729;
	private java.util.Map field_728;
	private java.util.List field_727;
	private WorldServer field_726;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1789_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1780_a(int a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1787_a(IChunkProvider a, int b, int c);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1788_a(boolean a, IProgressUpdate b);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1790_b();
	
	/**
	 * 
	 */
	public abstract Chunk MIDDLECRAFT_func_1783_b(int a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1781_c(int a, int b);
	
	/**
	 * 
	 */
	public abstract Chunk MIDDLECRAFT_func_1782_d(int a, int b);

}
