// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface interface ChunkCoordinates{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(int a, int b, int c)
	
	/**
	 * 
	 */
	public abstract int b(int a, int b, int c)
	
	/**
	 * 
	 */
	public abstract la c(int a, int b, int c)
	
	/**
	 * 
	 */
	public abstract boolean d(int a, int b, int c)

}
