// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ConsoleLogManager{
	// FIELDS
	public static java.util.logging.Logger a;
	
	// METHODS
	
	/**
	 * 
	 */
	public static void a()

}
