// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingRecipe{
	// FIELDS
	private int[] d;
	private ItemStack e;
	private int b;
	private int c;
	public final int a;
	
	// METHODS
	
	/**
	 * 
	 */
	public ItemStack b(int[] a)
	
	/**
	 * 
	 */
	public boolean a(int[] a)
	
	/**
	 * 
	 */
	private boolean a(int[] a, int b, int c, boolean d)
	
	/**
	 * 
	 */
	public int a()

}
