// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingInventoryChestCB extends CraftingInventoryCB {
	// FIELDS
	private IInventory field_20137;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_145_b(EntityPlayer a);

}
