// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingManager {
	// FIELDS
	private static final CraftingManager field_20155;
	private java.util.List field_20154;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract static CraftingManager a();
	
	/**
	 * 
	 */
	public abstract ItemStack a(int[] a);

}
