// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingInventoryFurnaceCB extends CraftingInventoryCB{
	// FIELDS
	 int f;
	 java.util.List g;
	 java.util.List d;
	 java.util.List e;
	private int b;
	private int c;
	private TileEntityFurnace a;
	private int h;
	
	// METHODS
	
	/**
	 * 
	 */
	 void a(Slot a)
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	 void a(EntityPlayer a, boolean b)
	
	/**
	 * 
	 */
	 Slot a(int a)
	
	/**
	 * 
	 */
	public void a(ICrafting a)
	
	/**
	 * 
	 */
	 boolean c(EntityPlayer a)
	
	/**
	 * 
	 */
	 Slot a(IInventory a, int b)
	
	/**
	 * 
	 */
	 ItemStack a(int a, int b, EntityPlayer c)
	
	/**
	 * 
	 */
	public boolean b(EntityPlayer a)
	
	/**
	 * 
	 */
	 void a(IInventory a)
	
	/**
	 * 
	 */
	 void a(EntityPlayer a)

}
