// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingRecipe {
	// FIELDS
	public int field_20168;
	private int field_20167;
	private int field_20171;
	private int[] field_20170;
	private ItemStack field_20169;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract int func_20165();
	
	/**
	 * *
	 */
	public abstract boolean func_20164(int[] a);
	
	/**
	 * *
	 */
	public abstract ItemStack func_20163(int[] a);

}
