// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingManager{
	// FIELDS
	private java.util.List b;
	private static final CraftingManager a;
	
	// METHODS
	
	/**
	 * 
	 */
	public ItemStack a(int[] a)
	
	/**
	 * 
	 */
	public static final CraftingManager a()
	
	/**
	 * 
	 */
	transient void a(ItemStack a, java.lang.Object[] b)

}
