// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingRecipe {
	// FIELDS
	public int field_20168;
	private int field_20167;
	private int field_20171;
	private int[] field_20170;
	private ItemStack field_20169;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_527_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_524_a(int[] a);
	
	/**
	 * 
	 */
	public abstract ItemStack MIDDLECRAFT_func_526_b(int[] a);

}
