// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingInventoryFurnaceCB extends CraftingInventoryCB{
	// FIELDS
	private TileEntityFurnace a;
	private int b;
	private int c;
	 ()V setChunkModified;
	private int h;
	
	// METHODS
	
	/**
	 * *
	 */
	 void func_20125();
	
	/**
	 * 
	 */
	public void a();
	
	/**
	 * 
	 */
	public void a(ICrafting a);
	
	/**
	 * 
	 */
	public boolean b(EntityPlayer a);

}
