// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingInventoryPlayerCB extends CraftingInventoryCB{
	// FIELDS
	public InventoryCrafting a;
	public IInventory b;
	public boolean c;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(EntityPlayer a)
	
	/**
	 * 
	 */
	public void a(IInventory a)
	
	/**
	 * 
	 */
	public boolean b(EntityPlayer a)

}
