// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class CraftingInventoryFurnaceCB extends CraftingInventoryCB {
	// FIELDS
	private TileEntityFurnace field_20139;
	private int field_20138;
	private int field_20141;
	private int field_20140;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract void func_20125();
	
	/**
	 * *
	 */
	public abstract void func_20128(ICrafting a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_100_b(EntityPlayer a);

}
