// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityBoat extends Entity {
	// FIELDS
	public int field_9178;
	private double field_9175;
	private double field_9173;
	private double field_9171;
	public int field_9177;
	public int field_436;
	private int field_9176;
	private double field_9174;
	private double field_9172;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_455_A();
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_456_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_452_a(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_458_a(EntityPlayer a);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_457_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_454_b_();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_453_c_();
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_448_d(Entity a);
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_451_j();
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB MIDDLECRAFT_func_449_q();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_450_v();

}
