// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityChicken extends EntityAnimals {
	// FIELDS
	public boolean field_392;
	public int field_396;
	public float field_391;
	public float field_395;
	public float field_394;
	public float field_393;
	public float field_390;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void G();
	
	/**
	 * 
	 */
	protected abstract void a(float a);
	
	/**
	 * 
	 */
	public abstract void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract java.lang.String d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String f();
	
	/**
	 * 
	 */
	protected abstract int g();

}
