// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityPlayerMP extends EntityPlayer{
	// FIELDS
	public java.util.List f;
	public double d;
	public double e;
	public net.minecraft.server.MienCrapftHurrvurr b;
	public ItemInWorldManager c;
	public NetServerHandler a;
	public double ak;
	public boolean al;
	public java.util.Set aj;
	public boolean am;
	private int bE;
	private int bH;
	private int bF;
	private int[] bG;
	
	// METHODS
	
	/**
	 * 
	 */
	public float s()
	
	/**
	 * 
	 */
	public int a(int a)
	
	/**
	 * 
	 */
	public void c(Entity a, int b)
	
	/**
	 * 
	 */
	public void G()
	
	/**
	 * 
	 */
	public void a(CraftingInventoryCB a, int b, int c)
	
	/**
	 * 
	 */
	public void F()
	
	/**
	 * 
	 */
	public void a(IInventory a)
	
	/**
	 * 
	 */
	private int c(ItemStack a)
	
	/**
	 * 
	 */
	public int[] E()
	
	/**
	 * 
	 */
	public void c(int a)
	
	/**
	 * 
	 */
	public void a(CraftingInventoryCB a, int b, ItemStack c)
	
	/**
	 * 
	 */
	public void a(CraftingInventoryCB a, java.util.List b)
	
	/**
	 * 
	 */
	public void a(int a, int b, int c)
	
	/**
	 * 
	 */
	public void e(Entity a)
	
	/**
	 * 
	 */
	public void K()
	
	/**
	 * 
	 */
	public boolean p()
	
	/**
	 * 
	 */
	public boolean a(Entity a, int b)
	
	/**
	 * 
	 */
	private void a(TileEntity a)
	
	/**
	 * 
	 */
	public void b(double a, boolean b)
	
	/**
	 * 
	 */
	public void k()
	
	/**
	 * 
	 */
	public void a(TileEntityFurnace a)
	
	/**
	 * 
	 */
	public void J()
	
	/**
	 * 
	 */
	public void I()
	
	/**
	 * 
	 */
	public void b_()
	
	/**
	 * 
	 */
	protected void a(double a, boolean b)
	
	/**
	 * 
	 */
	public void f(Entity a)
	
	/**
	 * 
	 */
	private void R()
	
	/**
	 * 
	 */
	public void H()
	
	/**
	 * 
	 */
	public void a(ItemStack a)

}
