// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityMobs extends EntityCreature{
	// FIELDS
	 boolean D;
	 boolean E;
	 boolean F;
	 boolean G;
	 boolean A;
	 boolean B;
	 boolean C;
	 float L;
	 boolean M;
	 float N;
	 double O;
	 float H;
	 float I;
	 float J;
	 float K;
	 float U;
	 boolean T;
	 java.util.Random W;
	 boolean V;
	 double Q;
	 double P;
	 float S;
	 float R;
	 int Y;
	 int X;
	 int Z;
	protected int f;
	 int g;
	 double n;
	 double o;
	 World l;
	 double m;
	 Entity j;
	 Entity k;
	 double h;
	 boolean i;
	 float w;
	 float v;
	 double u;
	 double t;
	 double s;
	 double r;
	 double q;
	 double p;
	 AxisAlignedBB z;
	 float y;
	 float x;
	 float bz;
	 int bw;
	 float bv;
	 float by;
	 int bx;
	 double bs;
	 double br;
	 double bu;
	 double bt;
	 float bn;
	 float bo;
	 int bp;
	 double bq;
	 boolean bj;
	 int bk;
	 float bl;
	 float bm;
	 int bf;
	 int bg;
	 float bh;
	 float bi;
	 int bb;
	 int bc;
	 int bd;
	 float be;
	 float aZ;
	 float aY;
	 float bA;
	 boolean aR;
	 java.lang.String aQ;
	 java.lang.String aT;
	 float aS;
	 int aV;
	 float aU;
	 boolean aX;
	 float aW;
	 float aI;
	 float aJ;
	 float aK;
	 float aL;
	 float aM;
	 float aN;
	 float aO;
	 boolean aP;
	 int aF;
	 float aG;
	 float aH;
	 int ba;
	 boolean ak;
	 int ai;
	 Entity aj;
	 int ac;
	 float bD;
	 int ad;
	 int aa;
	 boolean bB;
	 boolean ab;
	 float bC;
	 int ag;
	 int ah;
	 boolean ae;
	 boolean af;
	
	// METHODS
	
	/**
	 * 
	 */
	 AxisAlignedBB d(Entity a)
	
	/**
	 * 
	 */
	 double e(double a, double b, double c)
	
	/**
	 * 
	 */
	 java.lang.String d()
	
	/**
	 * 
	 */
	 void b(double a, double b, double c, float d, float e)
	
	/**
	 * 
	 */
	 void c(float a, float b)
	
	/**
	 * 
	 */
	 float b(float a)
	
	/**
	 * 
	 */
	 void A()
	
	/**
	 * 
	 */
	 void c(double a, double b, double c, float d, float e)
	
	/**
	 * 
	 */
	 void b(Entity a, int b)
	
	/**
	 * 
	 */
	 boolean x()
	
	/**
	 * 
	 */
	 double j()
	
	/**
	 * 
	 */
	 int[] E()
	
	/**
	 * 
	 */
	 boolean i(Entity a)
	
	/**
	 * 
	 */
	protected float a(int a, int b, int c)
	
	/**
	 * 
	 */
	 void f(double a, double b, double c)
	
	/**
	 * 
	 */
	 boolean v()
	
	/**
	 * 
	 */
	 boolean a(Material a)
	
	/**
	 * 
	 */
	 boolean c_()
	
	/**
	 * 
	 */
	 void b(EntityPlayer a)
	
	/**
	 * 
	 */
	 void e(Entity a)
	
	/**
	 * 
	 */
	 void d(int a)
	
	/**
	 * 
	 */
	 void a(Entity a, int b, double c, double d)
	
	/**
	 * 
	 */
	 void n()
	
	/**
	 * 
	 */
	 EntityItem a(int a, int b, float c)
	
	/**
	 * 
	 */
	 int hashCode()
	
	/**
	 * 
	 */
	public boolean a(Entity a, int b)
	
	/**
	 * 
	 */
	 java.lang.String w()
	
	/**
	 * 
	 */
	 boolean a(EntityPlayer a)
	
	/**
	 * 
	 */
	 AxisAlignedBB q()
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	 int g()
	
	/**
	 * 
	 */
	 void b(Entity a, float b)
	
	/**
	 * 
	 */
	 void a(double a, boolean b)
	
	/**
	 * 
	 */
	 void f(Entity a)
	
	/**
	 * 
	 */
	 float a(Entity a)
	
	/**
	 * 
	 */
	 Vec3D C()
	
	/**
	 * 
	 */
	 boolean r()
	
	/**
	 * 
	 */
	 Vec3D c(float a)
	
	/**
	 * 
	 */
	 float s()
	
	/**
	 * 
	 */
	 boolean b(double a, double b, double c)
	
	/**
	 * 
	 */
	 int b()
	
	/**
	 * 
	 */
	 void z()
	
	/**
	 * 
	 */
	 double d(double a, double b, double c)
	
	/**
	 * 
	 */
	 void l()
	
	/**
	 * 
	 */
	 boolean t()
	
	/**
	 * 
	 */
	 java.lang.String e()
	
	/**
	 * 
	 */
	public void G()
	
	/**
	 * 
	 */
	 NBTTagList a(double[] a)
	
	/**
	 * 
	 */
	 int i()
	
	/**
	 * 
	 */
	 java.lang.String f()
	
	/**
	 * 
	 */
	protected void a(Entity a, float b)
	
	/**
	 * 
	 */
	 void o()
	
	/**
	 * 
	 */
	 void c(int a)
	
	/**
	 * 
	 */
	 void b(float a, float b)
	
	/**
	 * 
	 */
	 float h()
	
	/**
	 * 
	 */
	 void b(int a)
	
	/**
	 * 
	 */
	 void D()
	
	/**
	 * 
	 */
	 void a(float a, float b, float c)
	
	/**
	 * 
	 */
	 void d(NBTTagCompound a)
	
	/**
	 * 
	 */
	 void O()
	
	/**
	 * 
	 */
	 void a(double a, double b, double c)
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a)
	
	/**
	 * 
	 */
	 double b(Entity a)
	
	/**
	 * 
	 */
	 void m()
	
	/**
	 * 
	 */
	protected Entity k()
	
	/**
	 * 
	 */
	 NBTTagList a(float[] a)
	
	/**
	 * 
	 */
	 void e(NBTTagCompound a)
	
	/**
	 * 
	 */
	 boolean y()
	
	/**
	 * 
	 */
	 boolean p()
	
	/**
	 * 
	 */
	 void a(float a, float b)
	
	/**
	 * 
	 */
	 void c()
	
	/**
	 * 
	 */
	 void Q()
	
	/**
	 * 
	 */
	 double B()
	
	/**
	 * 
	 */
	 void c(Entity a)
	
	/**
	 * 
	 */
	 boolean equals(java.lang.Object a)
	
	/**
	 * 
	 */
	public void b_()
	
	/**
	 * 
	 */
	 void a(float a)
	
	/**
	 * 
	 */
	 EntityItem b(int a, int b)
	
	/**
	 * 
	 */
	 void c(double a, double b, double c)
	
	/**
	 * 
	 */
	 void u()
	
	/**
	 * 
	 */
	 void P()
	
	/**
	 * 
	 */
	 boolean d_()
	
	/**
	 * 
	 */
	 boolean c(NBTTagCompound a)

}
