// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityMinecart{
	// FIELDS
	public Packet17AddToInventory a;
	public MaterialTransparent b;
	public boolean c;
	public boolean d;
	public boolean e;
	public float[] f;
	public int g;
	private float[] h;
	
	// METHODS
	
	/**
	 * 
	 */
	protected void a()
	
	/**
	 * 
	 */
	public static EntityMinecart a(int a)
	
	/**
	 * 
	 */
	public boolean a(int a, int b)
	
	/**
	 * 
	 */
	public float a(long a, float b)
	
	/**
	 * 
	 */
	public final void a(Packet17AddToInventory a)
	
	/**
	 * 
	 */
	public Vec3D a(java.io.File a)
	
	/**
	 * 
	 */
	protected void b()
	
	/**
	 * 
	 */
	public HashEntry2 c()

}
