// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityFireball extends Entity {
	// FIELDS
	public int field_9200;
	private int field_9197;
	private int field_9194;
	private boolean field_9192;
	private EntityLiving field_9191;
	private int field_9190;
	private int field_9189;
	public double field_9199;
	public double field_9198;
	public double field_9196;
	private int field_9195;
	private int field_9193;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract boolean a(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void b_();
	
	/**
	 * 
	 */
	public abstract boolean c_();

}
