// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityPlayerMP extends EntityPlayer {
	// FIELDS
	public NetServerHandler field_421;
	public java.util.Set field_420;
	public double field_418;
	public boolean field_12012;
	public boolean field_20064;
	public net.minecraft.server.MinecraftServer mcServer;
	private int field_9156;
	private int field_15004;
	private int[] field_20066;
	private int field_20065;
	public ItemInWorldManager field_425;
	public double field_9155;
	public double field_9154;
	public java.util.List loadedChunks;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int[] MIDDLECRAFT_func_879_E();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_886_F();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_888_G();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_890_H();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_904_I();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_905_J();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_906_K();
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_893_a(double a, boolean b);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_881_a(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_897_a(int a, int b, int c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_902_a(CraftingInventoryCB a, int b, int c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_900_a(CraftingInventoryCB a, int b, ItemStack c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_901_a(CraftingInventoryCB a, java.util.List b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_899_a(TileEntityFurnace a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_884_a(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_903_a(ItemStack a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_898_a(IInventory a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_894_b(double a, boolean b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_880_b_();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_885_c(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_889_c(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_892_e(Entity a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_883_f(Entity a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_878_k();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_895_p();
	
	/**
	 * 
	 */
	public abstract float MIDDLECRAFT_func_891_s();

}
