// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityFlying extends EntityLiving{
	// FIELDS
	 boolean D;
	 boolean E;
	 boolean F;
	 boolean G;
	 boolean A;
	 boolean B;
	 boolean C;
	 float L;
	 boolean M;
	 float N;
	 double O;
	 float H;
	 float I;
	 float J;
	 float K;
	 float U;
	 boolean T;
	 java.util.Random W;
	 boolean V;
	 double Q;
	 double P;
	 float S;
	 float R;
	 int Y;
	 int X;
	 int Z;
	 int g;
	 double n;
	 double o;
	 World l;
	 double m;
	 Entity j;
	 Entity k;
	 double h;
	 boolean i;
	 float w;
	 float v;
	 double u;
	 double t;
	 double s;
	 double r;
	 double q;
	 double p;
	 AxisAlignedBB z;
	 float y;
	 float x;
	 float bz;
	 int bw;
	 float bv;
	 float by;
	 int bx;
	 double bs;
	 double br;
	 double bu;
	 double bt;
	 float bn;
	 float bo;
	 int bp;
	 double bq;
	 boolean bj;
	 int bk;
	 float bl;
	 float bm;
	 int bf;
	 int bg;
	 float bh;
	 float bi;
	 int bb;
	 int bc;
	 int bd;
	 float be;
	 float aZ;
	 float aY;
	 float bA;
	 boolean aR;
	 java.lang.String aQ;
	 java.lang.String aT;
	 float aS;
	 int aV;
	 float aU;
	 boolean aX;
	 float aW;
	 float aI;
	 float aJ;
	 float aK;
	 float aL;
	 float aM;
	 float aN;
	 float aO;
	 boolean aP;
	 int aF;
	 float aG;
	 float aH;
	 int ba;
	 int ai;
	 float bD;
	 int ac;
	 int ad;
	 boolean bB;
	 int aa;
	 float bC;
	 boolean ab;
	 int ag;
	 int ah;
	 boolean ae;
	 boolean af;
	
	// METHODS
	
	/**
	 * 
	 */
	protected void a(float a)
	
	/**
	 * 
	 */
	public void c(float a, float b)
	
	/**
	 * 
	 */
	public boolean d_()

}
