// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityMinecart{
	// FIELDS
	public Packet17AddToInventory a;
	public MaterialTransparent b;
	public boolean c;
	public boolean d;
	public boolean e;
	public float[] f;
	public int g;
	private float[] h;
	
	// METHODS
	
	/**
	 * *
	 */
	protected void registerWorldChunkManager()
	
	/**
	 * 
	 */
	public static EntityMinecart a(int a)
	
	/**
	 * Will check if the x, z position specified is alright to be set as the map spawn point
	 */
	public boolean canCoordinateBeSpawn(int a, int b)
	
	/**
	 * *
	 */
	public float calculateCelestialAngle(long a, float b)
	
	/**
	 * *
	 */
	public final void registerWorld(Packet17AddToInventory a)
	
	/**
	 * Returns the chunk loader back for the world provider. Args: fileName
	 */
	public Vec3D getChunkLoader(java.io.File a)
	
	/**
	 * Creates the light to brightness table
	 */
	protected void generateLightBrightnessTable()
	
	/**
	 * Returns the chunk provider back for the world provider
	 */
	public HashEntry2 getChunkProvider()

}
