// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityArrow extends Entity {
	// FIELDS
	public int field_9184;
	private boolean field_9181;
	private int field_438;
	private int field_437;
	public EntityLiving field_439;
	private int field_9183;
	private int field_9182;
	private int field_9180;
	private int field_9179;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract void func_177(double a, double b, double c, float d, float e);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_319_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_320_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_321_b(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_318_b_();

}
