// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityItem extends Entity{
	// FIELDS
	private int f;
	public float d;
	private int e;
	public int b;
	public int c;
	public ItemStack a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void b(EntityPlayer a)
	
	/**
	 * 
	 */
	public void b_()
	
	/**
	 * 
	 */
	protected void b(int a)
	
	/**
	 * 
	 */
	private boolean g(double a, double b, double c)
	
	/**
	 * 
	 */
	public boolean a(Entity a, int b)
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a)
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a)
	
	/**
	 * 
	 */
	public boolean r()

}
