// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntitySlime extends EntityLiving {
	// FIELDS
	public float field_401;
	public float field_400;
	public int field_403;
	private int field_402;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_587_a();
	
	/**
	 * *
	 */
	public abstract void func_160(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_578_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_579_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_583_b(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_580_b_();
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_581_c();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_584_e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_585_f();
	
	/**
	 * 
	 */
	protected abstract int MIDDLECRAFT_func_586_g();
	
	/**
	 * 
	 */
	protected abstract float MIDDLECRAFT_func_588_h();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_582_l();

}
