// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntitySheep extends EntityAnimals {
	// FIELDS
	public boolean sheared;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_479_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_478_a(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_480_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_481_d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_482_e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_483_f();

}
