// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityBoat extends Entity{
	// FIELDS
	public int a;
	private double aj;
	private double ak;
	private double al;
	public int b;
	public int c;
	private int d;
	private double e;
	private ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public void A();
	
	/**
	 * 
	 */
	protected void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public boolean a(Entity a, int b);
	
	/**
	 * 
	 */
	public boolean a(EntityPlayer a);
	
	/**
	 * 
	 */
	protected void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public void b_();
	
	/**
	 * 
	 */
	public boolean c_();
	
	/**
	 * 
	 */
	public AxisAlignedBB d(Entity a);
	
	/**
	 * 
	 */
	public double j();
	
	/**
	 * 
	 */
	public AxisAlignedBB q();
	
	/**
	 * 
	 */
	public boolean v();

}
