// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityTNTPrimed extends Entity {
	// FIELDS
	public int fuse;
	
	// METHODS
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_443_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_444_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_441_b_();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_440_c_();

}
