// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Entity{
	// FIELDS
	public boolean D;
	public boolean E;
	public boolean F;
	public boolean G;
	public boolean A;
	public boolean B;
	public boolean C;
	public float L;
	protected boolean M;
	protected float N;
	public double O;
	public float H;
	public float I;
	public float J;
	public float K;
	public float U;
	public boolean T;
	protected java.util.Random W;
	public boolean V;
	public double Q;
	public double P;
	public float S;
	public float R;
	public int Y;
	public int X;
	public int Z;
	public int g;
	private double d;
	private double e;
	private int b;
	private boolean c;
	private static int a;
	public double n;
	public double o;
	public World l;
	public double m;
	public Entity j;
	public Entity k;
	public double h;
	public boolean i;
	public float w;
	public float v;
	public int ai;
	public double u;
	public double t;
	public double s;
	public double r;
	public double q;
	public double p;
	public int ac;
	public int ad;
	protected int aa;
	protected boolean ab;
	public int ag;
	public int ah;
	public final AxisAlignedBB z;
	protected boolean ae;
	public float y;
	public boolean af;
	public float x;
	
	// METHODS
	
	/**
	 * 
	 */
	public AxisAlignedBB d(Entity a)
	
	/**
	 * 
	 */
	public double e(double a, double b, double c)
	
	/**
	 * 
	 */
	public void b(double a, double b, double c, float d, float e)
	
	/**
	 * 
	 */
	public float b(float a)
	
	/**
	 * 
	 */
	public void A()
	
	/**
	 * 
	 */
	public void b(Entity a, int b)
	
	/**
	 * 
	 */
	public void c(double a, double b, double c, float d, float e)
	
	/**
	 * 
	 */
	public boolean x()
	
	/**
	 * 
	 */
	public double j()
	
	/**
	 * 
	 */
	public int[] E()
	
	/**
	 * 
	 */
	public void f(double a, double b, double c)
	
	/**
	 * 
	 */
	public boolean v()
	
	/**
	 * 
	 */
	public boolean c_()
	
	/**
	 * 
	 */
	public boolean a(Material a)
	
	/**
	 * 
	 */
	public void b(EntityPlayer a)
	
	/**
	 * 
	 */
	public void e(Entity a)
	
	/**
	 * 
	 */
	protected void n()
	
	/**
	 * 
	 */
	public EntityItem a(int a, int b, float c)
	
	/**
	 * 
	 */
	public int hashCode()
	
	/**
	 * 
	 */
	public boolean a(Entity a, int b)
	
	/**
	 * 
	 */
	protected final java.lang.String w()
	
	/**
	 * 
	 */
	public boolean a(EntityPlayer a)
	
	/**
	 * 
	 */
	public AxisAlignedBB q()
	
	/**
	 * 
	 */
	protected abstract void a(NBTTagCompound a)
	
	/**
	 * 
	 */
	protected void a(double a, boolean b)
	
	/**
	 * 
	 */
	public Vec3D C()
	
	/**
	 * 
	 */
	public float a(Entity a)
	
	/**
	 * 
	 */
	public boolean r()
	
	/**
	 * 
	 */
	public float s()
	
	/**
	 * 
	 */
	public boolean b(double a, double b, double c)
	
	/**
	 * 
	 */
	public void z()
	
	/**
	 * 
	 */
	public double d(double a, double b, double c)
	
	/**
	 * 
	 */
	public boolean t()
	
	/**
	 * 
	 */
	public void l()
	
	/**
	 * 
	 */
	protected transient NBTTagList a(double[] a)
	
	/**
	 * 
	 */
	protected void o()
	
	/**
	 * 
	 */
	protected void b(float a, float b)
	
	/**
	 * 
	 */
	protected void b(int a)
	
	/**
	 * 
	 */
	public void D()
	
	/**
	 * 
	 */
	public void d(NBTTagCompound a)
	
	/**
	 * 
	 */
	public void a(float a, float b, float c)
	
	/**
	 * 
	 */
	public void a(double a, double b, double c)
	
	/**
	 * 
	 */
	protected abstract void b(NBTTagCompound a)
	
	/**
	 * 
	 */
	public double b(Entity a)
	
	/**
	 * 
	 */
	public void m()
	
	/**
	 * 
	 */
	protected transient NBTTagList a(float[] a)
	
	/**
	 * 
	 */
	public void e(NBTTagCompound a)
	
	/**
	 * 
	 */
	public boolean y()
	
	/**
	 * 
	 */
	public boolean p()
	
	/**
	 * 
	 */
	protected void a(float a, float b)
	
	/**
	 * 
	 */
	public double B()
	
	/**
	 * 
	 */
	public void c(Entity a)
	
	/**
	 * 
	 */
	public boolean equals(java.lang.Object a)
	
	/**
	 * 
	 */
	public void b_()
	
	/**
	 * 
	 */
	protected void a(float a)
	
	/**
	 * 
	 */
	public EntityItem b(int a, int b)
	
	/**
	 * 
	 */
	public void c(double a, double b, double c)
	
	/**
	 * 
	 */
	protected void u()
	
	/**
	 * 
	 */
	public boolean c(NBTTagCompound a)

}
