// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityCow extends EntityAnimals {
	// FIELDS
	public boolean unusedBoolean;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_284_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_291_a(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_285_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_286_d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_287_e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_288_f();
	
	/**
	 * 
	 */
	protected abstract int MIDDLECRAFT_func_290_g();
	
	/**
	 * 
	 */
	protected abstract float MIDDLECRAFT_func_289_h();

}
