// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityItem extends Entity {
	// FIELDS
	public ItemStack item;
	public int field_9169;
	public int delayBeforeCanPickup;
	public float field_432;
	private int field_9170;
	private int health;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_609_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_608_a(Entity a, int b);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_607_b(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_610_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_611_b(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_605_b_();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_606_r();

}
