// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityGhast extends EntityFlying{
	// FIELDS
	public int f;
	private int ak;
	public double d;
	public int e;
	private Entity aj;
	public double b;
	public double c;
	public int a;
	
	// METHODS
	
	/**
	 * 
	 */
	private boolean a(double a, double b, double c, double d)
	
	/**
	 * 
	 */
	protected java.lang.String d()
	
	/**
	 * 
	 */
	protected float h()
	
	/**
	 * 
	 */
	protected java.lang.String e()
	
	/**
	 * 
	 */
	protected void c()
	
	/**
	 * 
	 */
	public int i()
	
	/**
	 * 
	 */
	protected java.lang.String f()
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	protected int g()

}
