// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityFish extends Entity {
	// FIELDS
	public int field_4134;
	private int field_4132;
	private boolean field_4129;
	private int field_6150;
	private int field_4125;
	private int field_4124;
	private int field_6149;
	private double field_6148;
	private double field_6147;
	private double field_6146;
	private double field_6145;
	private double field_6144;
	public EntityPlayer b;
	public Entity c;
	private int d;
	private int e;
	private int field_4126;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(double a, double b, double c, float d, float e);
	
	/**
	 * 
	 */
	public abstract void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void b_();
	
	/**
	 * 
	 */
	public abstract int c();

}
