// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityPigZombie extends BlockSoil{
	// FIELDS
	
	// METHODS
	
	/**
	 * Returns the ID of the items to drop on destruction.
	 */
	public int idDropped(int a, java.util.Random b)
	
	/**
	 * Ticks the block if it's been scheduled
	 */
	public void updateTick(Packet17AddToInventory a, int b, int c, int d, java.util.Random e)

}
