// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Entity {
	// FIELDS
	public boolean onGround;
	public boolean isTryingToMoveUp;
	public boolean field_9082;
	public boolean field_9080;
	public boolean field_9078;
	public boolean field_9077;
	public boolean isDead;
	public float yOffset;
	public float width;
	public float height;
	public float field_9075;
	public float field_9074;
	protected boolean entityWalks;
	protected float fallDistance;
	public double lastTickPosX;
	public double lastTickPosY;
	public double lastTickPosZ;
	public float field_9068;
	public float field_9067;
	public boolean field_9066;
	public float field_286;
	public boolean field_9065;
	protected java.util.Random rand;
	public int field_9063;
	public int field_9062;
	public int fire;
	private static int field_384;
	protected int maxAir;
	protected boolean field_9085;
	public int field_9083;
	public int air;
	protected boolean isImmuneToFire;
	public boolean field_276;
	public int field_307;
	public int field_305;
	public int field_303;
	private int field_6151;
	private boolean field_4131;
	private double field_4130;
	private double field_4128;
	public int field_331;
	public double renderDistanceWeight;
	public boolean field_329;
	public Entity riddenByEntity;
	public Entity ridingEntity;
	public World worldObj;
	public double prevPosX;
	public double prevPosY;
	public double prevPosZ;
	public double posX;
	public double posY;
	public double posZ;
	public double motionX;
	public double motionY;
	public double motionZ;
	public float rotationYaw;
	public float rotationPitch;
	public float prevRotationYaw;
	public float prevRotationPitch;
	public final AxisAlignedBB boundingBox;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void A();
	
	/**
	 * 
	 */
	public abstract double B();
	
	/**
	 * 
	 */
	public abstract Vec3D C();
	
	/**
	 * 
	 */
	public abstract void D();
	
	/**
	 * 
	 */
	public abstract int[] E();
	
	/**
	 * 
	 */
	public abstract void a(double a, double b, double c);
	
	/**
	 * 
	 */
	protected abstract void a(double a, boolean b);
	
	/**
	 * 
	 */
	protected abstract void a(float a);
	
	/**
	 * 
	 */
	protected abstract void a(float a, float b);
	
	/**
	 * 
	 */
	public abstract void a(float a, float b, float c);
	
	/**
	 * 
	 */
	public abstract EntityItem a(int a, int b, float c);
	
	/**
	 * 
	 */
	protected abstract void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract float a(Entity a);
	
	/**
	 * 
	 */
	public abstract boolean a(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract boolean a(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract boolean a(Material a);
	
	/**
	 * 
	 */
	protected abstract transient NBTTagList a(double[] a);
	
	/**
	 * 
	 */
	protected abstract transient NBTTagList a(float[] a);
	
	/**
	 * 
	 */
	public abstract boolean b(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract void b(double a, double b, double c, float d, float e);
	
	/**
	 * 
	 */
	public abstract float b(float a);
	
	/**
	 * 
	 */
	protected abstract void b(float a, float b);
	
	/**
	 * 
	 */
	protected abstract void b(int a);
	
	/**
	 * 
	 */
	public abstract EntityItem b(int a, int b);
	
	/**
	 * 
	 */
	protected abstract void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract double b(Entity a);
	
	/**
	 * 
	 */
	public abstract void b(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract void b(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract void b_();
	
	/**
	 * 
	 */
	public abstract void c(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract void c(double a, double b, double c, float d, float e);
	
	/**
	 * 
	 */
	public abstract boolean c(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void c(Entity a);
	
	/**
	 * 
	 */
	public abstract boolean c_();
	
	/**
	 * 
	 */
	public abstract double d(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract void d(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB d(Entity a);
	
	/**
	 * 
	 */
	public abstract double e(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract void e(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void e(Entity a);
	
	/**
	 * 
	 */
	public abstract boolean equals(java.lang.Object a);
	
	/**
	 * 
	 */
	public abstract void f(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract int hashCode();
	
	/**
	 * 
	 */
	public abstract double j();
	
	/**
	 * 
	 */
	public abstract void l();
	
	/**
	 * 
	 */
	public abstract void m();
	
	/**
	 * 
	 */
	protected abstract void n();
	
	/**
	 * 
	 */
	protected abstract void o();
	
	/**
	 * 
	 */
	public abstract boolean p();
	
	/**
	 * 
	 */
	public abstract AxisAlignedBB q();
	
	/**
	 * 
	 */
	public abstract boolean r();
	
	/**
	 * 
	 */
	public abstract float s();
	
	/**
	 * 
	 */
	public abstract boolean t();
	
	/**
	 * 
	 */
	protected abstract void u();
	
	/**
	 * 
	 */
	public abstract boolean v();
	
	/**
	 * 
	 */
	protected abstract java.lang.String w();
	
	/**
	 * 
	 */
	public abstract boolean x();
	
	/**
	 * 
	 */
	public abstract boolean y();
	
	/**
	 * 
	 */
	public abstract void z();

}
