// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityGhast extends EntityFlying {
	// FIELDS
	public int field_4099;
	private Entity field_4097;
	private int field_4103;
	public double field_4098;
	public double field_4104;
	public double field_4102;
	public int field_4101;
	public int field_4100;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean a();
	
	/**
	 * 
	 */
	protected abstract void c();
	
	/**
	 * 
	 */
	protected abstract java.lang.String d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String f();
	
	/**
	 * 
	 */
	protected abstract int g();
	
	/**
	 * 
	 */
	protected abstract float h();
	
	/**
	 * 
	 */
	public abstract int i();

}
