// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityTrackerEntry{
	// FIELDS
	public Entity a;
	public boolean b;
	public boolean c;
	public boolean d;
	public int e;
	public ()V setChunkModified;
	public int g;
	public int h;
	public int i;
	public int j;
	public int k;
	public double l;
	public double m;
	public double n;
	public int o;
	public boolean p;
	public java.util.Set q;
	private double r;
	private double s;
	private double t;
	private boolean u;
	private boolean v;
	
	// METHODS
	
	/**
	 * *
	 */
	 void func_12019(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public void a();
	
	/**
	 * 
	 */
	public void a(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public void a(java.util.List a);
	
	/**
	 * 
	 */
	public void a(Packet a);
	
	/**
	 * *
	 */
	 void func_12018(Packet a);
	
	/**
	 * 
	 */
	private Packet b();
	
	/**
	 * 
	 */
	public void b(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public void b(java.util.List a);
	
	/**
	 * 
	 */
	public void b(Packet a);
	
	/**
	 * *
	 */
	 void func_9219(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public void c(EntityPlayerMP a);
	
	/**
	 * *
	 */
	 boolean hr_equals(java.lang.Object a);
	
	/**
	 * 
	 */
	public boolean equals(java.lang.Object a);
	
	/**
	 * *
	 */
	 int hr_hashCode();
	
	/**
	 * 
	 */
	public int hashCode();

}
