// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntitySkeleton extends EntityMobs {
	// FIELDS
	private static ItemStack field_4108;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_984_G();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_986_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_985_a(Entity a, float b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_987_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_981_d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_982_e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_983_f();
	
	/**
	 * 
	 */
	protected abstract int MIDDLECRAFT_func_988_g();

}
