// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityPainting extends Entity {
	// FIELDS
	public int field_448;
	public EnumArt field_9185;
	private int field_452;
	private int field_9188;
	private int field_9187;
	private int field_9186;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(int a);
	
	/**
	 * 
	 */
	public abstract void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract boolean a(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void b_();
	
	/**
	 * 
	 */
	public abstract boolean c();
	
	/**
	 * 
	 */
	public abstract boolean c_();

}
