// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityTrackerEntry {
	// FIELDS
	public Entity field_909;
	public boolean field_9237;
	public boolean field_9236;
	public boolean field_9225;
	public int field_9235;
	public int field_9234;
	public int field_9233;
	public int field_9232;
	public int field_9231;
	public int field_9230;
	public int field_9229;
	public double field_9228;
	public double field_9227;
	public double field_9226;
	public int field_9221;
	public boolean field_900;
	public java.util.Set field_899;
	private double field_9224;
	private double field_9223;
	private double field_9222;
	private boolean field_12020;
	private boolean field_9220;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a();
	
	/**
	 * 
	 */
	public abstract void a(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public abstract void a(java.util.List a);
	
	/**
	 * 
	 */
	public abstract void a(Packet a);
	
	/**
	 * 
	 */
	public abstract void b(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public abstract void b(java.util.List a);
	
	/**
	 * 
	 */
	public abstract void b(Packet a);
	
	/**
	 * 
	 */
	public abstract void c(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public abstract boolean equals(java.lang.Object a);
	
	/**
	 * 
	 */
	public abstract int hashCode();

}
