// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityCreeper extends EntityMobs {
	// FIELDS
	 int field_406;
	 int field_405;
	 int field_408;
	 int field_407;
	 int field_12011;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1038_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_1045_a(Entity a, float b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1039_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1040_b_();
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_1041_c();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_1042_e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_1043_f();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1044_f(Entity a);
	
	/**
	 * 
	 */
	protected abstract int MIDDLECRAFT_func_1046_g();

}
