// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityMobs extends EntityCreature {
	// FIELDS
	protected int field_404;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1150_G();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1158_a();
	
	/**
	 * 
	 */
	protected abstract float MIDDLECRAFT_func_1155_a(int a, int b, int c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1156_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_1154_a(Entity a, float b);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1153_a(Entity a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1157_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1151_b_();
	
	/**
	 * 
	 */
	protected abstract Entity MIDDLECRAFT_func_1152_k();

}
