// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityCreeper extends EntityMobs{
	// FIELDS
	 int d;
	 int e;
	 int b;
	 int c;
	 int a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void b_()
	
	/**
	 * 
	 */
	public void f(Entity a)
	
	/**
	 * 
	 */
	protected java.lang.String e()
	
	/**
	 * 
	 */
	protected void c()
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a)
	
	/**
	 * 
	 */
	protected java.lang.String f()
	
	/**
	 * 
	 */
	protected void a(Entity a, float b)
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a)
	
	/**
	 * 
	 */
	protected int g()

}
