// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityChicken extends EntityArrow{
	// FIELDS
	public PlayerListBox a;
	public lg b;
	private Packet17AddToInventory c;
	private int h;
	private int i;
	private int j;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(BlockLog a)
	
	/**
	 * 
	 */
	public void a(lg a)
	
	/**
	 * 
	 */
	public boolean b(BlockLog a)

}
