// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityPig extends EntityAnimals {
	// FIELDS
	public boolean rideable;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_705_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_710_a(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_706_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_707_d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_708_e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_709_f();
	
	/**
	 * 
	 */
	protected abstract int MIDDLECRAFT_func_711_g();

}
