// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityAnimals extends EntityCreature {
	// FIELDS
	
	// METHODS
	
	/**
	 * Checks if the entity's current position is a valid location to spawn this entity.
	 */
	public abstract boolean getCanSpawnHere();
	
	/**
	 * *
	 */
	protected abstract float func_159(int a, int b, int c);
	
	/**
	 * (abstract) Protected helper method to write subclass entity data to NBT.
	 */
	public abstract void writeEntityToNBT(NBTTagCompound a);
	
	/**
	 * *
	 */
	public abstract int func_146();
	
	/**
	 * (abstract) Protected helper method to read subclass entity data from NBT.
	 */
	public abstract void readEntityFromNBT(NBTTagCompound a);

}
