// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityArrow extends Entity{
	// FIELDS
	public int a;
	private boolean aj;
	private int ak;
	private int al;
	public EntityLiving b;
	private int c;
	private int d;
	private int e;
	private ()V setChunkModified;
	
	// METHODS
	
	/**
	 * *
	 */
	 void func_177(double a, double b, double c, float d, float e);
	
	/**
	 * 
	 */
	public void a(double a, double b, double c, float d, float e);
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public void b(EntityPlayer a);
	
	/**
	 * 
	 */
	public void b_();

}
