// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityCreature extends EntityLiving{
	// FIELDS
	protected boolean ak;
	protected Entity aj;
	private PathEntity a;
	
	// METHODS
	
	/**
	 * 
	 */
	protected float a(int a, int b, int c)
	
	/**
	 * 
	 */
	protected void c()
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	protected void a(Entity a, float b)
	
	/**
	 * 
	 */
	protected Entity k()

}
