// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityFish extends Entity{
	// FIELDS
	private int f;
	private int d;
	private int e;
	public EntityPlayer b;
	public Entity c;
	public int a;
	private double at;
	private double as;
	private double ar;
	private double aq;
	private boolean ak;
	private int al;
	private int aj;
	private int ao;
	private double ap;
	private int am;
	private int an;
	
	// METHODS
	
	/**
	 * 
	 */
	public void b_()
	
	/**
	 * 
	 */
	public int c()
	
	/**
	 * 
	 */
	public void a(double a, double b, double c, float d, float e)
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a)
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a)

}
