// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntitySkeleton extends EntityMobs {
	// FIELDS
	private static ItemStack field_4108;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_432_G();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_434_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_433_a(Entity a, float b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_435_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_429_d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_430_e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_431_f();
	
	/**
	 * 
	 */
	protected abstract int MIDDLECRAFT_func_436_g();

}
