// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntitySheep extends EntityAnimals{
	// FIELDS
	public boolean a;
	
	// METHODS
	
	/**
	 * 
	 */
	protected java.lang.String d()
	
	/**
	 * 
	 */
	public boolean a(Entity a, int b)
	
	/**
	 * 
	 */
	protected java.lang.String e()
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a)
	
	/**
	 * 
	 */
	protected java.lang.String f()
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a)

}
