// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityCreeper extends EntityMobs{
	// FIELDS
	 int a;
	 int b;
	 int c;
	 int d;
	 int e;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected void a(Entity a, float b);
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public void b_();
	
	/**
	 * 
	 */
	protected void c();
	
	/**
	 * 
	 */
	protected java.lang.String e();
	
	/**
	 * 
	 */
	protected java.lang.String f();
	
	/**
	 * 
	 */
	public void f(Entity a);
	
	/**
	 * 
	 */
	protected int g();

}
