// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityPigZombie extends EntityZombie{
	// FIELDS
	private int b;
	private static final ItemStack c;
	private int a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void b_()
	
	/**
	 * 
	 */
	protected java.lang.String d()
	
	/**
	 * 
	 */
	public boolean a(Entity a, int b)
	
	/**
	 * 
	 */
	protected java.lang.String e()
	
	/**
	 * 
	 */
	public void G()
	
	/**
	 * 
	 */
	private void g(Entity a)
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a)
	
	/**
	 * 
	 */
	protected java.lang.String f()
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a)
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	protected int g()
	
	/**
	 * 
	 */
	protected Entity k()

}
