// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntitySkeleton extends EntityMobs {
	// FIELDS
	private static ItemStack field_4108;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void G();
	
	/**
	 * 
	 */
	public abstract void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract void a(Entity a, float b);
	
	/**
	 * 
	 */
	public abstract void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract java.lang.String d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String f();
	
	/**
	 * 
	 */
	protected abstract int g();

}
