// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityLiving extends BlockSoil{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	public boolean a(Packet17AddToInventory a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean a(Packet17AddToInventory a, int b, int c, int d, BlockLog e)
	
	/**
	 * 
	 */
	public void a(ChunkCoordinates a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(Packet17AddToInventory a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(Packet17AddToInventory a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public void b(Packet17AddToInventory a, int b, int c, int d, BlockLog e)
	
	/**
	 * 
	 */
	public boolean b(ChunkCoordinates a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public boolean c()
	
	/**
	 * 
	 */
	public void c(Packet17AddToInventory a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public IUpdatePlayerListBox d(Packet17AddToInventory a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean d(Packet17AddToInventory a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public void e(Packet17AddToInventory a, int b, int c, int d)
	
	/**
	 * 
	 */
	private boolean g(Packet17AddToInventory a, int b, int c, int d)

}
