// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityFireball extends Entity{
	// FIELDS
	public int a;
	private int aj;
	private int ak;
	private boolean al;
	private EntityLiving am;
	private int an;
	private int ao;
	public double b;
	public double c;
	public double d;
	private int e;
	private ()V setChunkModified;
	
	// METHODS
	
	/**
	 * Called when the entity is attacked.
	 */
	 boolean attackEntity(Entity a, int b);
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public boolean a(Entity a, int b);
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public void b_();
	
	/**
	 * *
	 */
	 boolean canBeCollidedWith();
	
	/**
	 * 
	 */
	public boolean c_();

}
