// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityCreature extends EntityLiving {
	// FIELDS
	private PathEntity field_388;
	protected Entity field_389;
	protected boolean field_387;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_658_a();
	
	/**
	 * 
	 */
	protected abstract float MIDDLECRAFT_func_656_a(int a, int b, int c);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_655_a(Entity a, float b);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_654_c();
	
	/**
	 * 
	 */
	protected abstract Entity MIDDLECRAFT_func_657_k();

}
