// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntityTracker{
	// FIELDS
	private int d;
	private MCHashTable b;
	private net.minecraft.server.MienCrapftHurrvurr c;
	private java.util.Set a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	public void a(Entity a, int b, int c, boolean d)
	
	/**
	 * 
	 */
	public void b(Entity a, Packet b)
	
	/**
	 * 
	 */
	public void a(Entity a, int b, int c)
	
	/**
	 * 
	 */
	public void a(EntityPlayerMP a)
	
	/**
	 * 
	 */
	public void a(Entity a, Packet b)
	
	/**
	 * 
	 */
	public void a(Entity a)
	
	/**
	 * 
	 */
	public void b(Entity a)

}
