// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EntitySpider extends EntityMobs {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_375_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_374_a(Entity a, float b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_376_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_371_d();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_372_e();
	
	/**
	 * 
	 */
	protected abstract java.lang.String MIDDLECRAFT_func_373_f();
	
	/**
	 * 
	 */
	protected abstract int MIDDLECRAFT_func_377_g();
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_369_j();
	
	/**
	 * 
	 */
	protected abstract Entity MIDDLECRAFT_func_370_k();

}
