// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract final class EnumCreatureType extends java.lang.Enum{
	// FIELDS
	public final int d;
	private static final ku[] e;
	public static final EnumCreatureType b;
	public final java.lang.Class c;
	public static final EnumCreatureType a;
	
	// METHODS
	
	/**
	 * 
	 */
	public static EnumCreatureType valueOf(java.lang.String a)
	
	/**
	 * 
	 */
	public static ku[] values()

}
