// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract final class EnumSkyBlock extends java.lang.Enum{
	// FIELDS
	private static final eb[] d;
	public static final EnumSkyBlock b;
	public final int c;
	public static final EnumSkyBlock a;
	
	// METHODS
	
	/**
	 * 
	 */
	public static eb[] values()
	
	/**
	 * 
	 */
	public static EnumSkyBlock valueOf(java.lang.String a)

}
