// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EnumMobType extends java.lang.Enum {
	// FIELDS
	public static EnumMobType ds_everything;
	public static EnumMobType ds_mobs;
	public static EnumMobType ds_players;
	private static EnumMobType[] field_990;
	
	// METHODS

}
