// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public enum EnumArt {
	
	// VALUES
	ie_Kebab,
	ie_Aztec,
	ie_Alban,
	ie_Aztec2,
	ie_Bomb,
	ie_Plant,
	ie_Wasteland,
	ie_Pool,
	ie_Courbet,
	ie_Sea,
	ie_Sunset,
	ie_Creebet,
	ie_Wanderer,
	ie_Graham,
	ie_Match,
	ie_Bust,
	ie_Stage,
	ie_Void,
	ie_SkullAndRoses,
	ie_Fighters,
	ie_Pointer,
	ie_Pigscene,
	ie_Skeleton,
	ie_DonkeyKong
	
	// METHODS

}
