// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract final class EnumMobType extends java.lang.Enum{
	// FIELDS
	private static final ds[] d;
	public static final EnumMobType b;
	public static final EnumMobType c;
	public static final EnumMobType a;
	
	// METHODS
	
	/**
	 * 
	 */
	public static EnumMobType valueOf(java.lang.String a)
	
	/**
	 * 
	 */
	public static ds[] values()

}
