// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class EnumCreatureType extends java.lang.Enum {
	// FIELDS
	public static EnumCreatureType ku_monster;
	public static EnumCreatureType ku_creature;
	public java.lang.Class field_4221;
	public int maxNumberOfEntityType;
	private static EnumCreatureType[] field_6155;
	
	// METHODS

}
