// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract final class EnumSkyBlock extends java.lang.Enum{
	// FIELDS
	public static final EnumSkyBlock a;
	public static final EnumSkyBlock b;
	public final int c;
	private static final eb[] d;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public static EnumSkyBlock valueOf(java.lang.String a);
	
	/**
	 * *
	 */
	 eb[] eb_values();
	
	/**
	 * 
	 */
	public static eb[] values();

}
