// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Explosion{
	// FIELDS
	public boolean a;
	public double b;
	public double c;
	public double d;
	public Entity e;
	public ()V setChunkModified;
	public java.util.Set g;
	private java.util.Random h;
	private World i;
	
	// METHODS
	
	/**
	 * *
	 */
	 void func_12023();
	
	/**
	 * 
	 */
	public void a();
	
	/**
	 * *
	 */
	 void func_732();
	
	/**
	 * 
	 */
	public void b();

}
