// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Explosion{
	// FIELDS
	public float f;
	public java.util.Set g;
	public double d;
	public Entity e;
	public double b;
	public double c;
	public boolean a;
	private java.util.Random h;
	private World i;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	public void b()

}
