// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class FontAllowedCharacters {
	// FIELDS
	public static java.lang.String field_20162;
	
	// METHODS

}
