// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class GuiStatsListener {
	// FIELDS
	 GuiStatsComponent statsComponent;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract void ld_actionPerformed(java.awt.event.ActionEvent a);

}
