// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class HashEntry extends java.util.logging.Formatter{
	// FIELDS
	final WorldGenLightStone2 a;
	
	// METHODS
	
	/**
	 * 
	 */
	public java.lang.String format(java.util.logging.LogRecord a)

}
