// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class HashEntry2{
	// FIELDS
	final int d;
	 java.lang.Object b;
	 HashEntry2 c;
	final long a;
	
	// METHODS
	
	/**
	 * 
	 */
	public final java.lang.Object b()
	
	/**
	 * 
	 */
	public final java.lang.String toString()
	
	/**
	 * 
	 */
	public final int hashCode()
	
	/**
	 * 
	 */
	public final boolean equals(java.lang.Object a)
	
	/**
	 * 
	 */
	public final long a()

}
