// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class HashEntry2 {
	// FIELDS
	 long field_1025;
	 java.lang.Object field_1024;
	 HashEntry2 field_1027;
	 int field_1026;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract long func_736();
	
	/**
	 * *
	 */
	public abstract java.lang.Object func_735();
	
	/**
	 * *
	 */
	public abstract boolean cr_equals(java.lang.Object a);
	
	/**
	 * *
	 */
	public abstract int cr_hashCode();
	
	/**
	 * *
	 */
	public abstract java.lang.String cr_toString();

}
