// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface IBlockAccess {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1643_a(int a, int b, int c);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1644_b(int a, int b, int c);
	
	/**
	 * 
	 */
	public abstract Material MIDDLECRAFT_func_1645_c(int a, int b, int c);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1646_d(int a, int b, int c);

}
