// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class IBlockAccess{
	// FIELDS
	private il[] a;
	
	// METHODS
	
	/**
	 * 
	 */
	public int a()
	
	/**
	 * 
	 */
	public BlockSponge a(int a)
	
	/**
	 * 
	 */
	public BlockSponge a(int a, int b)
	
	/**
	 * 
	 */
	public void a(int a, BlockSponge b)
	
	/**
	 * 
	 */
	public boolean a_(BlockLog a)
	
	/**
	 * 
	 */
	public java.lang.String b()
	
	/**
	 * 
	 */
	public int c()
	
	/**
	 * 
	 */
	public void d()

}
