// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface IChunkLoader {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_200_a();
	
	/**
	 * 
	 */
	public abstract Chunk MIDDLECRAFT_func_197_a(World a, int b, int c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_198_a(World a, Chunk b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_201_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_199_b(World a, Chunk b);

}
