// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface interface IChunkProvider{
	// FIELDS
	
	// METHODS
	
	/**
	 * Checks to see if a chunk exists at x, y
	 */
	 boolean chunkExists(int a, int b);
	
	/**
	 * 
	 */
	public abstract boolean a();
	
	/**
	 * 
	 */
	public abstract boolean a(int a, int b);
	
	/**
	 * 
	 */
	public abstract void a(IChunkProvider a, int b, int c);
	
	/**
	 * 
	 */
	public abstract boolean a(boolean a, IProgressUpdate b);
	
	/**
	 * *
	 */
	 boolean func_364();
	
	/**
	 * 
	 */
	public abstract boolean b();
	
	/**
	 * 
	 */
	public abstract Chunk b(int a, int b);

}
