// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface interface IChunkProvider{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean a(boolean a, IProgressUpdate b)
	
	/**
	 * 
	 */
	public abstract Chunk b(int a, int b)
	
	/**
	 * 
	 */
	public abstract boolean b()
	
	/**
	 * 
	 */
	public abstract boolean a(int a, int b)
	
	/**
	 * 
	 */
	public abstract boolean a()
	
	/**
	 * 
	 */
	public abstract void a(IChunkProvider a, int b, int c)

}
