// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface ICommandListener {
	// FIELDS
	
	// METHODS
	
	/**
	 * Logs the message with a level of INFO.
	 */
	public abstract void log(java.lang.String a);
	
	/**
	 * Gets the players username.
	 */
	public abstract java.lang.String getUsername();

}
