// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class InventoryPlayer extends TileEntityChest{
	// FIELDS
	public byte[] a;
	
	// METHODS
	
	/**
	 * 
	 */
	public byte a()
	
	/**
	 * 
	 */
	 void a(java.io.DataInput a)
	
	/**
	 * 
	 */
	 void a(java.io.DataOutput a)
	
	/**
	 * 
	 */
	public java.lang.String toString()

}
