// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class InventoryPlayer {
	// FIELDS
	public ItemStack[] mainInventory;
	public ItemStack[] armorInventory;
	public int currentItem;
	public boolean inventoryChanged;
	private EntityPlayer player;
	private ItemStack field_20074;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1439_a();
	
	/**
	 * 
	 */
	public abstract ItemStack MIDDLECRAFT_func_1440_a(int a);
	
	/**
	 * 
	 */
	public abstract ItemStack MIDDLECRAFT_func_1434_a(int a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1435_a(int a, ItemStack b);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1443_a(Entity a);
	
	/**
	 * 
	 */
	public abstract NBTTagList MIDDLECRAFT_func_1437_a(NBTTagList a);
	
	/**
	 * 
	 */
	public abstract float MIDDLECRAFT_func_1436_a(Block a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1433_a(ItemStack a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1451_a_(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract java.lang.String MIDDLECRAFT_func_1441_b();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1432_b(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1438_b(NBTTagList a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1444_b(Block a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1449_b(ItemStack a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1442_c();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1446_c(int a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1448_d();
	
	/**
	 * 
	 */
	public abstract ItemStack MIDDLECRAFT_func_1426_e();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1431_f();
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1445_g();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1447_h();
	
	/**
	 * 
	 */
	public abstract ItemStack MIDDLECRAFT_func_1450_i();

}
