// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class InventoryLargeChest {
	// FIELDS
	private java.lang.String name;
	private IInventory upperChest;
	private IInventory lowerChest;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a();
	
	/**
	 * 
	 */
	public abstract ItemStack a(int a);
	
	/**
	 * 
	 */
	public abstract ItemStack a(int a, int b);
	
	/**
	 * 
	 */
	public abstract void a(int a, ItemStack b);
	
	/**
	 * 
	 */
	public abstract boolean a_(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract java.lang.String b();
	
	/**
	 * 
	 */
	public abstract int c();
	
	/**
	 * 
	 */
	public abstract void d();

}
