// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface interface IProgressUpdate{
	// FIELDS
	
	// METHODS
	
	/**
	 * *
	 */
	 void func_438(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract void a(int a);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a);
	
	/**
	 * *
	 */
	 void displayLoadingString(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract void b(java.lang.String a);

}
