// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemArmor extends Item {
	// FIELDS
	public int field_254;
	public int field_257;
	public int field_256;
	public int field_255;
	private static int[] field_259;
	private static int[] field_258;
	
	// METHODS

}
