// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemFlintAndSteel extends Item{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(ItemStack a, EntityPlayer b, World c, int d, int e, int f, int g)

}
