// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemSoup extends ItemFood{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public ItemStack a(ItemStack a, World b, EntityPlayer c);

}
