// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemPickaxe extends ItemTool {
	// FIELDS
	private static Block[] goodAgainst;
	private int field_4208;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean a(Block a);

}
