// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemReed extends Item {
	// FIELDS
	private int field_253;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_955_a(ItemStack a, EntityPlayer b, World c, int d, int e, int f, int g);

}
