// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemTool extends Item{
	// FIELDS
	 Item D;
	 Item E;
	 Item F;
	 Item G;
	 Item A;
	 Item B;
	 Item C;
	 Item L;
	 Item M;
	 Item N;
	 Item O;
	 Item H;
	 Item I;
	 Item J;
	 Item K;
	 Item U;
	 Item T;
	 Item W;
	 Item V;
	 Item Q;
	 Item P;
	 Item S;
	 Item R;
	 Item Y;
	 Item X;
	 Item Z;
	 Item f;
	 Item g;
	 Item d;
	 Item e;
	 java.util.Random b;
	 gm[] c;
	protected int a;
	 Item n;
	 Item o;
	 Item l;
	 Item m;
	 Item j;
	 Item k;
	 Item h;
	 Item i;
	 Item w;
	 Item v;
	 Item u;
	 Item t;
	 Item s;
	 Item r;
	 Item q;
	 Item p;
	 Item z;
	 Item y;
	 Item x;
	private gv[] bb;
	private float bc;
	private int bd;
	 int aZ;
	 int aY;
	 Item aR;
	 Item aQ;
	 Item aT;
	 Item aS;
	 Item aV;
	 Item aU;
	 int aX;
	 int aW;
	 Item aI;
	 Item aJ;
	 Item aK;
	 Item aL;
	 Item aM;
	 Item aN;
	 Item aO;
	 Item aP;
	 Item aA;
	 Item aB;
	 Item aC;
	 Item aD;
	 Item aE;
	 Item aF;
	 Item aG;
	 Item aH;
	 Item az;
	 Item ay;
	 boolean ba;
	 Item at;
	 Item as;
	 Item ar;
	 Item aq;
	 Item ax;
	 Item aw;
	 Item av;
	 Item au;
	 Item ak;
	 Item al;
	 Item ai;
	 Item aj;
	 Item ao;
	 Item ap;
	 Item am;
	 Item an;
	 Item ac;
	 Item ad;
	 Item aa;
	 Item ab;
	 Item ag;
	 Item ah;
	 Item ae;
	 Item af;
	
	// METHODS
	
	/**
	 * 
	 */
	 Item a(java.lang.String a)
	
	/**
	 * 
	 */
	 boolean a(Block a)
	
	/**
	 * 
	 */
	 int b()
	
	/**
	 * 
	 */
	 ItemStack a(ItemStack a, World b, EntityPlayer c)
	
	/**
	 * 
	 */
	 Item d()
	
	/**
	 * 
	 */
	public void a(ItemStack a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public float a(ItemStack a, Block b)
	
	/**
	 * 
	 */
	 Item a(int a, int b)
	
	/**
	 * 
	 */
	 boolean a(ItemStack a, EntityPlayer b, World c, int d, int e, int f, int g)
	
	/**
	 * 
	 */
	 Item a(int a)
	
	/**
	 * 
	 */
	public void a(ItemStack a, EntityLiving b)
	
	/**
	 * 
	 */
	 int c()
	
	/**
	 * 
	 */
	public int a(Entity a)
	
	/**
	 * 
	 */
	 java.lang.String a()
	
	/**
	 * 
	 */
	 void b(ItemStack a, EntityLiving b)

}
