// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemSign extends Item{
	// FIELDS
	 Item D;
	 Item E;
	 Item F;
	 Item G;
	 Item A;
	 Item B;
	 Item C;
	 Item L;
	 Item M;
	 Item N;
	 Item O;
	 Item H;
	 Item I;
	 Item J;
	 Item K;
	 Item U;
	 Item T;
	 Item W;
	 Item V;
	 Item Q;
	 Item P;
	 Item S;
	 Item R;
	 Item Y;
	 Item X;
	 Item Z;
	 Item f;
	 Item g;
	 Item d;
	 Item e;
	 java.util.Random b;
	 gm[] c;
	 Item n;
	 Item o;
	 Item l;
	 Item m;
	 Item j;
	 Item k;
	 Item h;
	 Item i;
	 Item w;
	 Item v;
	 Item u;
	 Item t;
	 Item s;
	 Item r;
	 Item q;
	 Item p;
	 Item z;
	 Item y;
	 Item x;
	 int aZ;
	 int aY;
	 Item aR;
	 Item aQ;
	 Item aT;
	 Item aS;
	 Item aV;
	 Item aU;
	 int aX;
	 int aW;
	 Item aI;
	 Item aJ;
	 Item aK;
	 Item aL;
	 Item aM;
	 Item aN;
	 Item aO;
	 Item aP;
	 Item aA;
	 Item aB;
	 Item aC;
	 Item aD;
	 Item aE;
	 Item aF;
	 Item aG;
	 Item aH;
	 Item az;
	 Item ay;
	 boolean ba;
	 Item at;
	 Item as;
	 Item ar;
	 Item aq;
	 Item ax;
	 Item aw;
	 Item av;
	 Item au;
	 Item ak;
	 Item al;
	 Item ai;
	 Item aj;
	 Item ao;
	 Item ap;
	 Item am;
	 Item an;
	 Item ac;
	 Item ad;
	 Item aa;
	 Item ab;
	 Item ag;
	 Item ah;
	 Item ae;
	 Item af;
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(ItemStack a, EntityPlayer b, World c, int d, int e, int f, int g)

}
