// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemFlintAndSteel extends IMobs{
	// FIELDS
	public int a;
	public int b;
	
	// METHODS
	
	/**
	 * 
	 */
	protected void a(Packet1Login a)
	
	/**
	 * 
	 */
	protected void b(Packet1Login a)
	
	/**
	 * 
	 */
	public void b_()
	
	/**
	 * 
	 */
	public boolean c_()

}
