// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemPainting extends BlockSoil{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public void b(Packet17AddToInventory a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void e(Packet17AddToInventory a, int b, int c, int d)

}
