// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemBlock extends Item {
	// FIELDS
	private int field_272;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract java.lang.String MIDDLECRAFT_func_362_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_361_a(ItemStack a, EntityPlayer b, World c, int d, int e, int f, int g);

}
