// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemSword extends Item {
	// FIELDS
	private int field_4210;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a(Entity a);
	
	/**
	 * 
	 */
	public abstract void a(ItemStack a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract float a(ItemStack a, Block b);
	
	/**
	 * 
	 */
	public abstract void a(ItemStack a, EntityLiving b);

}
