// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemBucket{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public static void a(Packet1Login a, java.io.DataOutput b)
	
	/**
	 * *
	 */
	public static void writeGzippedCompoundToOutputStream(Packet1Login a, java.io.OutputStream b)
	
	/**
	 * 
	 */
	public static Packet1Login a(java.io.DataInput a)
	
	/**
	 * 
	 */
	public static Packet1Login a(java.io.InputStream a)

}
