// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemFishingRod extends Item {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract ItemStack MIDDLECRAFT_func_396_a(ItemStack a, World b, EntityPlayer c);

}
