// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemRecord extends Item {
	// FIELDS
	private java.lang.String recordName;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1022_a(ItemStack a, EntityPlayer b, World c, int d, int e, int f, int g);

}
