// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemInWorldManager{
	// FIELDS
	public EntityPlayer a;
	private World b;
	private float c;
	private float d;
	private int e;
	private ()V setChunkModified;
	private int g;
	private int h;
	private int i;
	
	// METHODS
	
	/**
	 * *
	 */
	 void func_324(int a, int b, int c);
	
	/**
	 * 
	 */
	public void a();
	
	/**
	 * 
	 */
	public void a(int a, int b, int c);
	
	/**
	 * 
	 */
	public void a(int a, int b, int c, int d);
	
	/**
	 * 
	 */
	public boolean a(EntityPlayer a, World b, ItemStack c);
	
	/**
	 * 
	 */
	public boolean a(EntityPlayer a, World b, ItemStack c, int d, int e, int f, int g);
	
	/**
	 * *
	 */
	 boolean func_323(int a, int b, int c);
	
	/**
	 * 
	 */
	public boolean b(int a, int b, int c);
	
	/**
	 * *
	 */
	 boolean func_325(int a, int b, int c);
	
	/**
	 * 
	 */
	public boolean c(int a, int b, int c);

}
