// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemMinecart extends IMobs{
	// FIELDS
	public int a;
	
	// METHODS
	
	/**
	 * (abstract) Protected helper method to write subclass entity data to NBT.
	 */
	protected void writeEntityToNBT(Packet1Login a)
	
	/**
	 * (abstract) Protected helper method to read subclass entity data from NBT.
	 */
	protected void readEntityFromNBT(Packet1Login a)
	
	/**
	 * Called to update the entity's position/logic.
	 */
	public void onUpdate()
	
	/**
	 * *
	 */
	private void explode()
	
	/**
	 * *
	 */
	public boolean canBeCollidedWith()

}
