// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemSaddle extends Item {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(ItemStack a, EntityLiving b);
	
	/**
	 * 
	 */
	public abstract void b(ItemStack a, EntityLiving b);

}
