// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemTool extends Item{
	// FIELDS
	protected int a;
	private gv[] bb;
	private float bc;
	private int bd;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public int a(Entity a);
	
	/**
	 * 
	 */
	public void a(ItemStack a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public float a(ItemStack a, Block b);
	
	/**
	 * 
	 */
	public void a(ItemStack a, EntityLiving b);

}
