// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ItemSpade extends ItemTool{
	// FIELDS
	private static gv[] bb;
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(Block a)

}
