// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface IWorldAccess {
	// FIELDS
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract void updateAllRenderers();
	
	/**
	 * *
	 */
	public abstract void func_683(int a, int b, int c);
	
	/**
	 * *
	 */
	public abstract void markBlockRangeNeedsUpdate(int a, int b, int c, int d, int e, int f);
	
	/**
	 * *
	 */
	public abstract void func_686(int a, int b, int c, TileEntity d);
	
	/**
	 * *
	 */
	public abstract void obtainEntitySkin(Entity a);
	
	/**
	 * Spawns a particle. Arg: particleType, x, y, z, velX, velY, velZ
	 */
	public abstract void spawnParticle(java.lang.String a, double b, double c, double d, double e, double f, double g);
	
	/**
	 * Plays the specified sound. Arg: x, y, z, soundName, unknown1, unknown2
	 */
	public abstract void playSound(java.lang.String a, double b, double c, double d, float e, float f);
	
	/**
	 * Plays the specified record. Arg: recordName, x, y, z
	 */
	public abstract void playRecord(java.lang.String a, int b, int c, int d);
	
	/**
	 * *
	 */
	public abstract void func_688(Entity a);

}
