// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MaterialLiquid extends Material{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a();
	
	/**
	 * 
	 */
	public boolean c();
	
	/**
	 * Returns if blocks of these materials are liquids.
	 */
	 boolean getIsLiquid();
	
	/**
	 * 
	 */
	public boolean d();

}
