// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Material extends ItemBlock{
	// FIELDS
	private int a;
	
	// METHODS
	
	/**
	 * *
	 */
	public boolean generate(Packet17AddToInventory a, java.util.Random b, int c, int d, int e)

}
