// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MaterialLiquid extends Material {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_291_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_290_c();
	
	/**
	 * Returns if blocks of these materials are liquids.
	 */
	public abstract boolean getIsLiquid();

}
