// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Material {
	// FIELDS
	public static final Material air;
	public static final Material ground;
	public static final Material wood;
	public static final Material rock;
	public static final Material iron;
	public static final Material water;
	public static final Material lava;
	public static final Material leaves;
	public static final Material plants;
	public static final Material sponge;
	public static final Material cloth;
	public static final Material fire;
	public static final Material sand;
	public static final Material circuits;
	public static final Material glass;
	public static final Material tnt;
	public static final Material unused;
	public static final Material ice;
	public static final Material snow;
	public static final Material builtSnow;
	public static final Material cactus;
	public static final Material clay;
	public static final Material pumpkin;
	public static final Material field_4212;
	private boolean canBurn;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean a();
	
	/**
	 * 
	 */
	public abstract boolean b();
	
	/**
	 * 
	 */
	public abstract boolean c();
	
	/**
	 * 
	 */
	public abstract boolean d();
	
	/**
	 * 
	 */
	public abstract boolean e();

}
