// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MaterialLogic extends Material {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_138_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_139_b();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_140_c();

}
