// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MathHelper extends IMobs{
	// FIELDS
	public BlockSponge a;
	public int b;
	public int c;
	public float d;
	private int e;
	private int f;
	
	// METHODS
	
	/**
	 * (abstract) Protected helper method to write subclass entity data to NBT.
	 */
	public void writeEntityToNBT(Packet1Login a)
	
	/**
	 * Called when the entity is attacked.
	 */
	public boolean attackEntity(IMobs a, int b)
	
	/**
	 * Will deal the specified amount of damage to the entity if the entity isn't immune to fire damage. Args: amountDamage
	 */
	protected void dealFireDamage(int a)
	
	/**
	 * (abstract) Protected helper method to read subclass entity data from NBT.
	 */
	public void readEntityFromNBT(Packet1Login a)
	
	/**
	 * Called by a player entity when they collide with an entity
	 */
	public void onCollideWithPlayer(BlockLog a)
	
	/**
	 * Called to update the entity's position/logic.
	 */
	public void onUpdate()
	
	/**
	 * 
	 */
	private boolean g(double a, double b, double c)
	
	/**
	 * Returns if this entity is in water and will end up adding the waters velocity to the entity
	 */
	public boolean handleWaterMovement()

}
