// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MCHashTable2 {
	// FIELDS
	private transient HashEntry2[] field_949;
	private transient int field_948;
	private int field_952;
	private float field_951;
	private transient volatile int field_950;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract java.lang.Object a(long a);
	
	/**
	 * 
	 */
	public abstract void a(long a, java.lang.Object b);
	
	/**
	 * 
	 */
	public abstract java.lang.Object b(long a);

}
