// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MCHashTable{
	// FIELDS
	private final float d;
	private transient volatile int e;
	private transient int b;
	private int c;
	private transient iv[] a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	private static int g(int a)
	
	/**
	 * 
	 */
	public boolean b(int a)
	
	/**
	 * 
	 */
	private static int a(int a, int b)
	
	/**
	 * 
	 */
	final HashEntry c(int a)
	
	/**
	 * 
	 */
	private void h(int a)
	
	/**
	 * 
	 */
	public java.lang.Object d(int a)
	
	/**
	 * 
	 */
	private void a(iv[] a)
	
	/**
	 * 
	 */
	private void a(int a, int b, java.lang.Object c, int d)
	
	/**
	 * 
	 */
	public void a(int a, java.lang.Object b)
	
	/**
	 * 
	 */
	public java.lang.Object a(int a)
	
	/**
	 * 
	 */
	final HashEntry e(int a)
	
	/**
	 * 
	 */
	static int f(int a)

}
