// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MCHashTable {
	// FIELDS
	private transient HashEntry[] slots;
	private transient int count;
	private int threshold;
	private float growFactor;
	private transient volatile int versionStamp;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a();
	
	/**
	 * 
	 */
	public abstract java.lang.Object a(int a);
	
	/**
	 * 
	 */
	public abstract void a(int a, java.lang.Object b);
	
	/**
	 * 
	 */
	public abstract boolean b(int a);
	
	/**
	 * 
	 */
	public abstract java.lang.Object d(int a);

}
