// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract final class MCHashTable extends java.lang.Enum{
	// FIELDS
	public final int A;
	public final int B;
	public final int C;
	private static final ie[] D;
	public static final MCHashTable a;
	public static final MCHashTable b;
	public static final MCHashTable c;
	public static final MCHashTable d;
	public static final MCHashTable e;
	public static final MCHashTable f;
	public static final MCHashTable g;
	public static final MCHashTable h;
	public static final MCHashTable i;
	public static final MCHashTable j;
	public static final MCHashTable k;
	public static final MCHashTable l;
	public static final MCHashTable m;
	public static final MCHashTable n;
	public static final MCHashTable o;
	public static final MCHashTable p;
	public static final MCHashTable q;
	public static final MCHashTable r;
	public static final MCHashTable s;
	public static final MCHashTable t;
	public static final MCHashTable u;
	public static final MCHashTable v;
	public static final MCHashTable w;
	public static final MCHashTable x;
	public final java.lang.String y;
	public final int z;
	
	// METHODS
	
	/**
	 * 
	 */
	public static MCHashTable valueOf(java.lang.String a)
	
	/**
	 * 
	 */
	public static ie[] values()

}
