// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MetadataChunkBlock {
	// FIELDS
	public final EnumSkyBlock field_957;
	public int field_956;
	public int field_962;
	public int field_961;
	public int field_960;
	public int field_959;
	public int field_958;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean a(int a, int b, int c, int d, int e, int f);
	
	/**
	 * 
	 */
	public abstract void a(World a);

}
