// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MinecraftException extends java.lang.RuntimeException {
	// FIELDS
	
	// METHODS

}
