// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MinecraftServer {
	// FIELDS
	public static java.util.logging.Logger a;
	public static java.util.HashMap b;
	public NetworkListenThread c;
	public PropertyManager d;
	public WorldServer e;
	public ServerConfigurationManager f;
	public boolean g;
	 int h;
	public java.lang.String i;
	public int j;
	public EntityTracker k;
	public boolean l;
	public boolean m;
	public boolean n;
	private boolean o;
	private java.util.List p;
	private java.util.List q;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1979_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1986_a(IUpdatePlayerListBox a);
	
	/**
	 * 
	 */
	public abstract java.io.File MIDDLECRAFT_func_1988_a(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1982_a(java.lang.String a, ICommandListener b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1983_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1989_b(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract java.lang.String MIDDLECRAFT_func_1990_c();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1980_run();

}
