// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class MobSpawnerBase {
	// FIELDS
	public static final MobSpawnerBase rainforest;
	public static final MobSpawnerBase swampland;
	public static final MobSpawnerBase seasonalForest;
	public static final MobSpawnerBase forest;
	public static final MobSpawnerBase savanna;
	public static final MobSpawnerBase shrubland;
	public static final MobSpawnerBase taiga;
	public static final MobSpawnerBase desert;
	public static final MobSpawnerBase plains;
	public static final MobSpawnerBase iceDesert;
	public static final MobSpawnerBase tundra;
	public static final MobSpawnerBase hell;
	public java.lang.String biomeName;
	public int field_6162;
	public byte topBlock;
	public byte fillerBlock;
	public int field_6161;
	protected java.lang.Class[] biomeMonsters;
	protected java.lang.Class[] biomeCreatures;
	private static jq[] biomeLookupTable;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract static void a();
	
	/**
	 * 
	 */
	public abstract static MobSpawnerBase a(double a, double b);
	
	/**
	 * 
	 */
	public abstract static MobSpawnerBase a(float a, float b);
	
	/**
	 * 
	 */
	protected abstract MobSpawnerBase a(int a);
	
	/**
	 * 
	 */
	protected abstract MobSpawnerBase a(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract java.lang.Class[] a(EnumCreatureType a);
	
	/**
	 * 
	 */
	protected abstract MobSpawnerBase b();
	
	/**
	 * 
	 */
	protected abstract MobSpawnerBase b(int a);

}
