// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTBase{
	// FIELDS
	private static final NBTBase a;
	private java.util.List b;
	
	// METHODS
	
	/**
	 * 
	 */
	public static final NBTBase a()
	
	/**
	 * 
	 */
	transient void a(BlockSponge a, java.lang.Object[] b)
	
	/**
	 * 
	 */
	public BlockSponge a(int[] a)

}
