// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTBase {
	// FIELDS
	private java.lang.String key;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_669_a();
	
	/**
	 * Gets the key corresponding to the tag, or an empty string if none set.
	 */
	public abstract java.lang.String getKey();
	
	/**
	 * Sets the key for this tag and returns this for convenience.
	 */
	public abstract NBTBase setKey(java.lang.String a);

}
