// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTBase{
	// FIELDS
	private java.lang.String a;
	
	// METHODS
	
	/**
	 * 
	 */
	abstract void a(java.io.DataOutput a)
	
	/**
	 * 
	 */
	public static void a(NBTBase a, java.io.DataOutput b)
	
	/**
	 * 
	 */
	abstract void a(java.io.DataInput a)
	
	/**
	 * 
	 */
	public abstract byte a()
	
	/**
	 * 
	 */
	public NBTBase m(java.lang.String a)
	
	/**
	 * 
	 */
	public static java.lang.String b(byte a)
	
	/**
	 * 
	 */
	public static NBTBase b(java.io.DataInput a)
	
	/**
	 * 
	 */
	public java.lang.String c()
	
	/**
	 * 
	 */
	public static NBTBase a(byte a)

}
