// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagEnd extends NBTBase {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_894_a();
	
	/**
	 * *
	 */
	public abstract java.lang.String kr_toString();

}
