// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagShort extends NBTBase{
	// FIELDS
	public short a;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public byte a();
	
	/**
	 * 
	 */
	 void a(java.io.DataInput a);
	
	/**
	 * 
	 */
	 void a(java.io.DataOutput a);
	
	/**
	 * *
	 */
	 java.lang.String gr_toString();
	
	/**
	 * 
	 */
	public java.lang.String toString();

}
