// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagLong extends NBTBase {
	// FIELDS
	public long longValue;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_281_a();
	
	/**
	 * *
	 */
	public abstract java.lang.String e_toString();

}
