// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagString extends BlockSoil{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a()
	
	/**
	 * 
	 */
	public boolean a(Packet17AddToInventory a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void a(Packet17AddToInventory a, int b, int c, int d, java.util.Random e)
	
	/**
	 * 
	 */
	protected boolean b(int a)
	
	/**
	 * 
	 */
	public void b(Packet17AddToInventory a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public IUpdatePlayerListBox d(Packet17AddToInventory a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean f(Packet17AddToInventory a, int b, int c, int d)
	
	/**
	 * 
	 */
	protected final void g(Packet17AddToInventory a, int b, int c, int d)

}
