// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagInt extends NBTBase {
	// FIELDS
	public int intValue;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_148_a();
	
	/**
	 * *
	 */
	public abstract java.lang.String bz_toString();

}
