// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagByte extends NBTBase {
	// FIELDS
	public byte byteValue;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte a();
	
	/**
	 * 
	 */
	public abstract java.lang.String toString();

}
