// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagCompound extends NBTBase {
	// FIELDS
	private java.util.Map tagMap;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte a();
	
	/**
	 * 
	 */
	public abstract boolean a(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, byte b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, double b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, float b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, int b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, long b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, NBTTagCompound b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, NBTBase b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, java.lang.String b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, short b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, boolean b);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, byte[] b);
	
	/**
	 * 
	 */
	public abstract byte b(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract short c(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract int d(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract long e(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract float f(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract double g(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract java.lang.String h(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract byte[] i(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract NBTTagCompound j(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract NBTTagList k(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract boolean l(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract java.lang.String toString();

}
