// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagDouble extends NBTBase {
	// FIELDS
	public double doubleValue;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_762_a();
	
	/**
	 * 
	 */
	public abstract java.lang.String MIDDLECRAFT_func_763_toString();

}
