// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagString extends NBTBase {
	// FIELDS
	public java.lang.String stringValue;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_1617_a();
	
	/**
	 * 
	 */
	public abstract java.lang.String MIDDLECRAFT_func_1618_toString();

}
