// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagShort extends NBTBase {
	// FIELDS
	public short shortValue;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_531_a();
	
	/**
	 * *
	 */
	public abstract java.lang.String gr_toString();

}
