// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagByteArray extends NBTBase {
	// FIELDS
	public byte[] byteArray;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_1263_a();
	
	/**
	 * 
	 */
	public abstract java.lang.String MIDDLECRAFT_func_1264_toString();

}
