// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NBTTagList extends NBTBase {
	// FIELDS
	private java.util.List tagList;
	private byte tagType;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract byte MIDDLECRAFT_func_338_a();
	
	/**
	 * Retrieves the tag at the specified index from the list.
	 */
	public abstract NBTBase tagAt(int a);
	
	/**
	 * Adds the provided tag to the end of the list. There is no check to verify this tag is of the same type as any previous tag.
	 */
	public abstract void setTag(NBTBase a);
	
	/**
	 * Returns the number of tags in the list.
	 */
	public abstract int tagCount();
	
	/**
	 * *
	 */
	public abstract java.lang.String es_toString();

}
