// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NetHandler{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(Packet29DestroyEntity a)
	
	/**
	 * 
	 */
	public void a(Packet5PlayerInventory a)
	
	/**
	 * 
	 */
	public void a(Packet39 a)
	
	/**
	 * 
	 */
	public void a(Packet2Handshake a)
	
	/**
	 * 
	 */
	public void a(Packet130 a)
	
	/**
	 * 
	 */
	public void a(Packet100 a)
	
	/**
	 * 
	 */
	public void a(Packet15Place a)
	
	/**
	 * 
	 */
	public void a(Packet28 a)
	
	/**
	 * 
	 */
	public void a(Packet3Chat a)
	
	/**
	 * 
	 */
	public void a(Packet53BlockChange a)
	
	/**
	 * 
	 */
	public void a(Packet101 a)
	
	/**
	 * 
	 */
	public void a(Packet14BlockDig a)
	
	/**
	 * 
	 */
	public void a(Packet6SpawnPosition a)
	
	/**
	 * 
	 */
	public void a(Packet18ArmAnimation a)
	
	/**
	 * 
	 */
	public void a(Packet105 a)
	
	/**
	 * 
	 */
	public void a(Packet52MultiBlockChange a)
	
	/**
	 * 
	 */
	public void a(Packet1Login a)
	
	/**
	 * 
	 */
	public void a(Packet30Entity a)
	
	/**
	 * 
	 */
	public void a(Packet a)
	
	/**
	 * 
	 */
	public void a(Packet23VehicleSpawn a)
	
	/**
	 * 
	 */
	public void a(Packet102 a)
	
	/**
	 * 
	 */
	public void a(Packet9 a)
	
	/**
	 * 
	 */
	public void a(Packet21PickupSpawn a)
	
	/**
	 * 
	 */
	public void a(Packet106 a)
	
	/**
	 * 
	 */
	public void a(Packet24MobSpawn a)
	
	/**
	 * 
	 */
	public void a(Packet10Flying a)
	
	/**
	 * 
	 */
	public void a(Packet103 a)
	
	/**
	 * 
	 */
	public void a(Packet104 a)
	
	/**
	 * 
	 */
	public void a(Packet20NamedEntitySpawn a)
	
	/**
	 * 
	 */
	public void a(Packet60 a)
	
	/**
	 * 
	 */
	public void a(Packet7 a)
	
	/**
	 * 
	 */
	public void a(Packet4UpdateTime a)
	
	/**
	 * 
	 */
	public void a(Packet22Collect a)
	
	/**
	 * 
	 */
	public void a(Packet51MapChunk a)
	
	/**
	 * 
	 */
	public void a(Packet38 a)
	
	/**
	 * 
	 */
	public void a(Packet16BlockItemSwitch a)
	
	/**
	 * 
	 */
	public void a(Packet50PreChunk a)
	
	/**
	 * 
	 */
	public void a(Packet255KickDisconnect a)
	
	/**
	 * 
	 */
	public void a(java.lang.String a, java.lang.Object[] b)
	
	/**
	 * 
	 */
	public void a(Packet34EntityTeleport a)
	
	/**
	 * 
	 */
	public void a(Packet8 a)

}
