// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NetHandler {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_967_a(Packet7 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_944_a(Packet1Login a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_980_a(Packet106 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_970_a(Packet9 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_958_a(Packet3Chat a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_974_a(Packet102 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_950_a(Packet20NamedEntitySpawn a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_964_a(Packet6SpawnPosition a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_952_a(Packet34EntityTeleport a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_957_a(Packet22Collect a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_971_a(Packet60 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_955_a(Packet29DestroyEntity a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_940_a(Packet51MapChunk a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_949_a(Packet50PreChunk a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_959_a(Packet23VehicleSpawn a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_969_a(Packet8 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_973_a(Packet101 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_948_a(Packet53BlockChange a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_951_a(Packet30Entity a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_965_a(Packet28 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_977_a(Packet130 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_953_a(Packet15Place a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_961_a(Packet2Handshake a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_963_a(Packet4UpdateTime a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_954_a(Packet16BlockItemSwitch a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_975_a(Packet103 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_945_a(Packet10Flying a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_972_a(Packet100 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_968_a(Packet38 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_962_a(Packet24MobSpawn a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_942_a(java.lang.String a, java.lang.Object[] b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_947_a(Packet14BlockDig a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_946_a(Packet52MultiBlockChange a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_976_a(Packet104 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_941_a(Packet a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_943_a(Packet255KickDisconnect a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_978_a(Packet105 a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_956_a(Packet21PickupSpawn a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_979_a(Packet5PlayerInventory a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_960_a(Packet18ArmAnimation a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_966_a(Packet39 a);

}
