// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NetHandler {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(Packet7 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet1Login a);
	
	/**
	 * 
	 */
	public abstract void a(Packet106 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet9 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet3Chat a);
	
	/**
	 * 
	 */
	public abstract void a(Packet102 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet20NamedEntitySpawn a);
	
	/**
	 * 
	 */
	public abstract void a(Packet6SpawnPosition a);
	
	/**
	 * 
	 */
	public abstract void a(Packet34EntityTeleport a);
	
	/**
	 * 
	 */
	public abstract void a(Packet22Collect a);
	
	/**
	 * 
	 */
	public abstract void a(Packet60 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet29DestroyEntity a);
	
	/**
	 * 
	 */
	public abstract void a(Packet51MapChunk a);
	
	/**
	 * 
	 */
	public abstract void a(Packet50PreChunk a);
	
	/**
	 * 
	 */
	public abstract void a(Packet23VehicleSpawn a);
	
	/**
	 * 
	 */
	public abstract void a(Packet8 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet101 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet53BlockChange a);
	
	/**
	 * 
	 */
	public abstract void a(Packet30Entity a);
	
	/**
	 * 
	 */
	public abstract void a(Packet28 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet130 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet15Place a);
	
	/**
	 * 
	 */
	public abstract void a(Packet2Handshake a);
	
	/**
	 * 
	 */
	public abstract void a(Packet4UpdateTime a);
	
	/**
	 * 
	 */
	public abstract void a(Packet16BlockItemSwitch a);
	
	/**
	 * 
	 */
	public abstract void a(Packet103 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet10Flying a);
	
	/**
	 * 
	 */
	public abstract void a(Packet100 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet38 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet24MobSpawn a);
	
	/**
	 * 
	 */
	public abstract void a(java.lang.String a, java.lang.Object[] b);
	
	/**
	 * 
	 */
	public abstract void a(Packet14BlockDig a);
	
	/**
	 * 
	 */
	public abstract void a(Packet52MultiBlockChange a);
	
	/**
	 * 
	 */
	public abstract void a(Packet104 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet a);
	
	/**
	 * 
	 */
	public abstract void a(Packet255KickDisconnect a);
	
	/**
	 * 
	 */
	public abstract void a(Packet105 a);
	
	/**
	 * 
	 */
	public abstract void a(Packet21PickupSpawn a);
	
	/**
	 * 
	 */
	public abstract void a(Packet5PlayerInventory a);
	
	/**
	 * 
	 */
	public abstract void a(Packet18ArmAnimation a);
	
	/**
	 * 
	 */
	public abstract void a(Packet39 a);

}
