// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NetworkListenThread{
	// FIELDS
	private int f;
	private java.util.ArrayList g;
	private java.net.ServerSocket d;
	private java.lang.Thread e;
	public volatile boolean b;
	public net.minecraft.server.MienCrapftHurrvurr c;
	public static java.util.logging.Logger a;
	private java.util.ArrayList h;
	
	// METHODS
	
	/**
	 * 
	 */
	static int b(NetworkListenThread a)
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	private void a(NetLoginHandler a)
	
	/**
	 * 
	 */
	static java.net.ServerSocket a(NetworkListenThread a)
	
	/**
	 * 
	 */
	static void a(NetworkListenThread a, NetLoginHandler b)
	
	/**
	 * 
	 */
	public void a(NetServerHandler a)

}
