// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NetworkMasterThread{
	// FIELDS
	private static java.util.Map a;
	private static java.util.Map b;
	private static java.util.Map c;
	private static java.util.Map d;
	
	// METHODS
	
	/**
	 * 
	 */
	public static IMobs a(Packet1Login a, Packet17AddToInventory b)
	
	/**
	 * 
	 */
	public static int a(IMobs a)
	
	/**
	 * 
	 */
	private static void a(java.lang.Class a, java.lang.String b, int c)
	
	/**
	 * 
	 */
	public static IMobs a(java.lang.String a, Packet17AddToInventory b)
	
	/**
	 * 
	 */
	public static java.lang.String b(IMobs a)

}
