// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class NetworkAcceptThread extends java.lang.Thread{
	// FIELDS
	final net.minecraft.server.MinecraftServer a;
	final NetworkListenThread b;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * *
	 */
	 void dx_run();
	
	/**
	 * 
	 */
	public void run();

}
