// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NetworkReaderThread extends EntityMinecart{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	public boolean a(int a, int b)
	
	/**
	 * 
	 */
	public float a(long a, float b)
	
	/**
	 * 
	 */
	public Vec3D a(java.io.File a)
	
	/**
	 * 
	 */
	protected void b()
	
	/**
	 * 
	 */
	public HashEntry2 c()

}
