// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NetworkWriterThread{
	// FIELDS
	public final int a;
	public final int b;
	public final int c;
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean equals(java.lang.Object a)
	
	/**
	 * 
	 */
	public int hashCode()

}
