// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NibbleArray {
	// FIELDS
	public byte[] data;
	
	// METHODS
	
	/**
	 * Returns if the byte array is null or not.
	 */
	public abstract boolean isValid();
	
	/**
	 * Returns the nibble of data corresponding to the passed in i,j,k. j is at most 6 bits, k is at most 4.
	 */
	public abstract int getNibble(int a, int b, int c);
	
	/**
	 * Sets the nibble of data at i << 11 | k << 7 | j to l.
	 */
	public abstract void setNibble(int a, int b, int c, int d);

}
