// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NoiseGeneratorOctaves extends NoiseGenerator {
	// FIELDS
	private NoiseGeneratorPerlin[] field_939;
	private int field_938;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract double func_647(double a, double b);
	
	/**
	 * *
	 */
	public abstract double[] func_648(double[] a, double b, double c, double d, int e, int f, int g, double h, double i, double j);
	
	/**
	 * *
	 */
	public abstract double[] func_4103(double[] a, int b, int c, int d, int e, double f, double g, double h);

}
