// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NoiseGenerator2{
	// FIELDS
	private static final double f;
	private static final double g;
	private static int[][] d;
	private int[] e;
	public double b;
	public double c;
	public double a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(double[] a, double b, double c, int d, int e, double f, double g, double h)
	
	/**
	 * 
	 */
	private static double a(int[] a, double b, double c)
	
	/**
	 * 
	 */
	private static int a(double a)

}
