// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NoiseGeneratorPerlin extends NoiseGenerator {
	// FIELDS
	public double xCoord;
	public double yCoord;
	public double zCoord;
	private int[] permutations;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract double a(double a, double b);
	
	/**
	 * 
	 */
	public abstract double a(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract double a(int a, double b, double c);
	
	/**
	 * 
	 */
	public abstract double a(int a, double b, double c, double d);
	
	/**
	 * 
	 */
	public abstract void a(double[] a, double b, double c, double d, int e, int f, int g, double h, double i, double j, double k);
	
	/**
	 * 
	 */
	public abstract double b(double a, double b, double c);

}
