// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NoiseGeneratorPerlin extends NoiseGenerator {
	// FIELDS
	public double xCoord;
	public double yCoord;
	public double zCoord;
	private int[] permutations;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_136_a(double a, double b);
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_132_a(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_134_a(int a, double b, double c);
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_135_a(int a, double b, double c, double d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_137_a(double[] a, double b, double c, double d, int e, int f, int g, double h, double i, double j, double k);
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_133_b(double a, double b, double c);

}
