// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class NoiseGeneratorOctaves extends NoiseGenerator{
	// FIELDS
	private int b;
	private ar[] a;
	
	// METHODS
	
	/**
	 * 
	 */
	public double a(double a, double b)
	
	/**
	 * 
	 */
	public double[] a(double[] a, double b, double c, double d, int e, int f, int g, double h, double i, double j)
	
	/**
	 * 
	 */
	public double[] a(double[] a, int b, int c, int d, int e, double f, double g, double h)

}
