// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet100 extends Packet {
	// FIELDS
	public int field_20013;
	public int field_20012;
	public java.lang.String field_20015;
	public int field_20014;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1425_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1422_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1423_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1424_a(java.io.DataOutputStream a);

}
