// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet23VehicleSpawn extends Packet {
	// FIELDS
	public int entityId;
	public int xPosition;
	public int yPosition;
	public int zPosition;
	public int type;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_711_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_710_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_708_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_709_a(java.io.DataOutputStream a);

}
