// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet60 extends Packet{
	// FIELDS
	public double a;
	public double b;
	public double c;
	public float d;
	public java.util.Set e;
	
	// METHODS
	
	/**
	 * 
	 */
	public int a()
	
	/**
	 * 
	 */
	public void a(NetHandler a)
	
	/**
	 * 
	 */
	public void a(java.io.DataInputStream a)
	
	/**
	 * 
	 */
	public void a(java.io.DataOutputStream a)

}
