// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet1Login extends Packet{
	// FIELDS
	public int a;
	public java.lang.String b;
	public java.lang.String c;
	public long d;
	public byte e;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * Abstract. Return the size of the packet (not counting the header).
	 */
	 int getPacketSize();
	
	/**
	 * 
	 */
	public int a();
	
	/**
	 * 
	 */
	public void a(NetHandler a);
	
	/**
	 * 
	 */
	public void a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public void a(java.io.DataOutputStream a);

}
