// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet106 extends Packet {
	// FIELDS
	public int field_20034;
	public short field_20033;
	public boolean field_20035;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_173_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_170_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_171_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_172_a(java.io.DataOutputStream a);

}
