// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet51MapChunk{
	// FIELDS
	public static java.util.logging.Logger a;
	private java.io.File b;
	
	// METHODS
	
	/**
	 * Writes the player data to disk from the specified PlayerEntityMP.
	 */
	public void writePlayerData(WorldGenCactus a)
	
	/**
	 * Reads the player data from disk into the specified PlayerEntityMP.
	 */
	public void readPlayerData(WorldGenCactus a)

}
