// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet14BlockDig{
	// FIELDS
	private static float[] a;
	
	// METHODS
	
	/**
	 * 
	 */
	public static final float a(double a)
	
	/**
	 * 
	 */
	public static double a(double a, double b)
	
	/**
	 * 
	 */
	public static final float a(float a)
	
	/**
	 * 
	 */
	public static int b(double a)
	
	/**
	 * 
	 */
	public static final float b(float a)
	
	/**
	 * 
	 */
	public static final float c(float a)
	
	/**
	 * 
	 */
	public static int d(float a)
	
	/**
	 * 
	 */
	public static float e(float a)

}
