// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet103 extends Packet {
	// FIELDS
	public int field_20017;
	public int field_20016;
	public ItemStack field_20018;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_633_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_630_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_631_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_632_a(java.io.DataOutputStream a);

}
