// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet52MultiBlockChange extends BlockStep{
	// FIELDS
	public int a;
	public int b;
	public java.lang.String c;
	public int d;
	
	// METHODS
	
	/**
	 * 
	 */
	public int a()
	
	/**
	 * 
	 */
	public void a(Packet28 a)
	
	/**
	 * 
	 */
	public void a(java.io.DataInputStream a)
	
	/**
	 * 
	 */
	public void a(java.io.DataOutputStream a)

}
