// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet1Login extends Packet {
	// FIELDS
	public int protocolVersion;
	public java.lang.String username;
	public java.lang.String password;
	public long field_4026;
	public byte field_4025;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_113_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_112_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_110_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_111_a(java.io.DataOutputStream a);

}
