// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet8 extends Packet{
	// FIELDS
	public int a;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * 
	 */
	public int a();
	
	/**
	 * 
	 */
	public void a(NetHandler a);
	
	/**
	 * 
	 */
	public void a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public void a(java.io.DataOutputStream a);

}
