// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet {
	// FIELDS
	private static java.util.Map packetIdToClassMap;
	private static java.util.Map packetClassToIdMap;
	public long field_20009;
	public boolean isChunkDataPacket;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_790_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_789_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_787_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_788_a(java.io.DataOutputStream a);
	
	/**
	 * Returns the ID of this packet.
	 */
	public abstract int getPacketId();

}
