// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet13PlayerLookMove extends Packet10Flying {
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_752_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_750_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_751_a(java.io.DataOutputStream a);

}
