// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet39 extends Packet {
	// FIELDS
	public int field_6044;
	public int field_6043;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1967_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1970_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1968_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1969_a(java.io.DataOutputStream a);

}
