// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class Packet11PlayerPosition{
	// FIELDS
	final javax.swing.JTextField a;
	final EnumArt b;
	
	// METHODS
	
	/**
	 * 
	 */
	public void actionPerformed(java.awt.event.ActionEvent a)

}
