// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet15Place extends Packet{
	// FIELDS
	public int d;
	public ItemStack e;
	public int b;
	public int c;
	public int a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(java.io.DataInputStream a)
	
	/**
	 * 
	 */
	public void a(NetHandler a)
	
	/**
	 * 
	 */
	public int a()
	
	/**
	 * 
	 */
	public void a(java.io.DataOutputStream a)

}
