// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet255KickDisconnect extends Packet {
	// FIELDS
	public java.lang.String reason;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_915_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_914_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_912_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_913_a(java.io.DataOutputStream a);

}
