// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet32EntityLook extends Packet30Entity{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public int a();
	
	/**
	 * 
	 */
	public void a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public void a(java.io.DataOutputStream a);

}
