// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet38 extends Packet {
	// FIELDS
	public int field_9016;
	public byte field_9015;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_704_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_703_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_701_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_702_a(java.io.DataOutputStream a);

}
