// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet22Collect extends Packet {
	// FIELDS
	public int collectedEntityId;
	public int collectorEntityId;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_221_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_220_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_218_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_219_a(java.io.DataOutputStream a);

}
