// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet21PickupSpawn extends Packet{
	// FIELDS
	public int a;
	public int b;
	public int c;
	public int d;
	public byte e;
	public ()V setChunkModified;
	public byte g;
	public int h;
	public int i;
	
	// METHODS
	
	/**
	 * 
	 */
	public int a();
	
	/**
	 * 
	 */
	public void a(NetHandler a);
	
	/**
	 * 
	 */
	public void a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public void a(java.io.DataOutputStream a);

}
