// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet38 extends EntityFlying{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public int a()
	
	/**
	 * 
	 */
	public void a(java.io.DataInputStream a)
	
	/**
	 * 
	 */
	public void a(java.io.DataOutputStream a)

}
