// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Packet28 extends Packet {
	// FIELDS
	public int field_6040;
	public int field_6039;
	public int field_6042;
	public int field_6041;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1070_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1069_a(NetHandler a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1067_a(java.io.DataInputStream a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1068_a(java.io.DataOutputStream a);

}
