// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PathEntity{
	// FIELDS
	private final b[] b;
	private int c;
	public final int a;
	
	// METHODS
	
	/**
	 * 
	 */
	public Vec3D a(Entity a)
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	public boolean b()

}
