// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PathPoint {
	// FIELDS
	public final int xCoord;
	public final int yCoord;
	public final int zCoord;
	public final int hash;
	 int index;
	 float totalPathDistance;
	 float distanceToNext;
	 float distanceToTarget;
	 PathPoint previous;
	public boolean isFirst;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean a();
	
	/**
	 * 
	 */
	public abstract float a(PathPoint a);
	
	/**
	 * 
	 */
	public abstract boolean equals(java.lang.Object a);
	
	/**
	 * 
	 */
	public abstract int hashCode();
	
	/**
	 * 
	 */
	public abstract java.lang.String toString();

}
