// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Pathfinder {
	// FIELDS
	private IBlockAccess worldMap;
	private Path path;
	private MCHashTable pointMap;
	private PathPoint[] pathOptions;
	
	// METHODS
	
	/**
	 * Creates a path from an entity to a specified location within a minimum distance
	 */
	public abstract PathEntity createEntityPathTo(Entity a, int b, int c, int d, float e);
	
	/**
	 * 
	 */
	public abstract PathEntity MIDDLECRAFT_func_438_a(Entity a, Entity b, float c);

}
