// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PathEntity {
	// FIELDS
	public int pathLength;
	private PathPoint[] points;
	private int pathIndex;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_458_a();
	
	/**
	 * 
	 */
	public abstract Vec3D MIDDLECRAFT_func_460_a(Entity a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_459_b();

}
