// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PlayerManager extends ItemBlock{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(Packet17AddToInventory a, java.util.Random b, int c, int d, int e)

}
