// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PlayerManager {
	// FIELDS
	private java.util.List field_9216;
	private MCHashTable2 field_9215;
	private java.util.List field_833;
	private net.minecraft.server.MinecraftServer mcServer;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1578_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1580_a(int a, int b, int c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1581_a(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1585_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1582_b(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1584_c(EntityPlayerMP a);

}
