// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PlayerManager {
	// FIELDS
	private java.util.List field_9216;
	private MCHashTable2 field_9215;
	private java.util.List field_833;
	private net.minecraft.server.MinecraftServer mcServer;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a();
	
	/**
	 * 
	 */
	public abstract void a(int a, int b, int c);
	
	/**
	 * 
	 */
	public abstract void a(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public abstract int b();
	
	/**
	 * 
	 */
	public abstract void b(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public abstract void c(EntityPlayerMP a);

}
