// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PlayerNBTManager{
	// FIELDS
	public static java.util.logging.Logger a;
	private java.io.File b;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * Writes the player data to disk from the specified PlayerEntityMP.
	 */
	 void writePlayerData(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public void a(EntityPlayerMP a);
	
	/**
	 * Reads the player data from disk into the specified PlayerEntityMP.
	 */
	 void readPlayerData(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public void b(EntityPlayerMP a);

}
