// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PlayerNBTManager {
	// FIELDS
	public static java.util.logging.Logger logger;
	private java.io.File worldFile;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(EntityPlayerMP a);
	
	/**
	 * 
	 */
	public abstract void b(EntityPlayerMP a);

}
