// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PlayerListBox extends javax.swing.JList{
	// FIELDS
	private net.minecraft.server.MinecraftServer a;
	private int b;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * Updates the Jlist with a new model.
	 */
	 void update();
	
	/**
	 * 
	 */
	public void a();

}
