// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PlayerListBox extends javax.swing.JList{
	// FIELDS
	private int b;
	private net.minecraft.server.MienCrapftHurrvurr a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a()

}
