// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PropertyManager{
	// FIELDS
	private java.util.Properties b;
	private java.io.File c;
	public static java.util.logging.Logger a;
	
	// METHODS
	
	/**
	 * 
	 */
	public java.lang.String a(java.lang.String a, java.lang.String b)
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	public boolean a(java.lang.String a, boolean b)
	
	/**
	 * 
	 */
	public int a(java.lang.String a, int b)
	
	/**
	 * 
	 */
	public void b()

}
