// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class PropertyManager {
	// FIELDS
	public static java.util.logging.Logger logger;
	private java.util.Properties serverProperties;
	private java.io.File serverPropertiesFile;
	
	// METHODS
	
	/**
	 * Generates a new properties file.
	 */
	public abstract void generateNewProperties();
	
	/**
	 * Returns an integer property. If the property doesn't exist the default is returned.
	 */
	public abstract int getIntProperty(java.lang.String a, int b);
	
	/**
	 * Returns a string property. If the property doesn't exist the default is returned.
	 */
	public abstract java.lang.String getStringProperty(java.lang.String a, java.lang.String b);
	
	/**
	 * Returns a boolean property. If the property doesn't exist the default is returned.
	 */
	public abstract boolean getBooleanProperty(java.lang.String a, boolean b);
	
	/**
	 * Writes the properties to the properties file.
	 */
	public abstract void saveProperties();

}
