// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class RecipesArmor {
	// FIELDS
	private java.lang.String[][] field_20174;
	private java.lang.Object[][] field_20173;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract void func_20172(CraftingManager a);

}
