// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class RecipeSorter{
	// FIELDS
	final CraftingManager a;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * *
	 */
	 int func_20107(CraftingRecipe a, CraftingRecipe b);
	
	/**
	 * 
	 */
	public int a(CraftingRecipe a, CraftingRecipe b);
	
	/**
	 * *
	 */
	 int kd_compare(java.lang.Object a, java.lang.Object b);
	
	/**
	 * 
	 */
	public volatile int compare(java.lang.Object a, java.lang.Object b);

}
