// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class RecipesTools {
	// FIELDS
	private java.lang.String[][] field_20158;
	private java.lang.Object[][] field_20157;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(CraftingManager a);

}
