// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class RecipesIngots {
	// FIELDS
	private java.lang.Object[][] field_20160;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(CraftingManager a);

}
