// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class RecipesArmor{
	// FIELDS
	private java.lang.Object[][] b;
	private java.lang.String[][] a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(CraftingManager a)

}
