// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class ServerGuiFocusAdapter extends java.awt.event.FocusAdapter{
	// FIELDS
	final ServerGUI a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void focusGained(java.awt.event.FocusEvent a)

}
