// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class ServerGuiCommandListener {
	// FIELDS
	 javax.swing.JTextField textField;
	 ServerGUI mcServerGui;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract void ae_actionPerformed(java.awt.event.ActionEvent a);

}
