// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ServerGUI extends javax.swing.JComponent {
	// FIELDS
	public static java.util.logging.Logger logger;
	private net.minecraft.server.MinecraftServer mcServer;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void b(java.lang.String a);
	
	/**
	 * 
	 */
	public abstract java.lang.String c();

}
