// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class ServerWindowAdapter extends java.awt.event.WindowAdapter {
	// FIELDS
	 net.minecraft.server.MinecraftServer mcServer;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_69_windowClosing(java.awt.event.WindowEvent a);

}
