// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class SlotArmor extends Slot{
	// FIELDS
	final int a;
	final CraftingInventoryPlayerCB b;
	
	// METHODS
	
	/**
	 * 
	 */
	public int a()
	
	/**
	 * 
	 */
	public boolean a(ItemStack a)

}
