// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class SlotArmor extends Slot{
	// FIELDS
	 int d;
	 int e;
	final CraftingInventoryPlayerCB b;
	 int c;
	final int a;
	
	// METHODS
	
	/**
	 * 
	 */
	 void d()
	
	/**
	 * 
	 */
	 void b(ItemStack a)
	
	/**
	 * 
	 */
	 ItemStack c()
	
	/**
	 * 
	 */
	public boolean a(ItemStack a)
	
	/**
	 * 
	 */
	 void b()
	
	/**
	 * 
	 */
	public int a()
	
	/**
	 * 
	 */
	 ItemStack a(int a)
	
	/**
	 * 
	 */
	 boolean a(IInventory a, int b)

}
