// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class SlotCrafting extends Slot {
	// FIELDS
	private IInventory field_20103;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1918_a(ItemStack a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1919_b();

}
