// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Slot {
	// FIELDS
	private int field_20097;
	private IInventory field_20096;
	public int field_20100;
	public int field_20099;
	public int field_20098;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_509_a();
	
	/**
	 * *
	 */
	public abstract ItemStack func_20088(int a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_508_a(ItemStack a);
	
	/**
	 * *
	 */
	public abstract boolean func_20090(IInventory a, int b);
	
	/**
	 * *
	 */
	public abstract void func_20091();
	
	/**
	 * *
	 */
	public abstract void func_20089(ItemStack a);
	
	/**
	 * *
	 */
	public abstract ItemStack func_20092();
	
	/**
	 * *
	 */
	public abstract void func_20094();

}
