// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class SlotArmor extends Slot {
	// FIELDS
	final int field_20102;
	final CraftingInventoryPlayerCB field_20101;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int a();
	
	/**
	 * 
	 */
	public abstract boolean a(ItemStack a);

}
