// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class SlotCrafting extends Slot{
	// FIELDS
	 int d;
	 int e;
	 int c;
	private final IInventory a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void b()
	
	/**
	 * 
	 */
	public boolean a(ItemStack a)

}
