// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract final class StepSoundSand extends StepSound{
	// FIELDS
	
	// METHODS

}
