// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class StepSound{
	// FIELDS
	public final java.lang.String a;
	public final float b;
	public final float c;
	 ()V setChunkModified;
	
	// METHODS
	
	/**
	 * *
	 */
	 float func_738();
	
	/**
	 * 
	 */
	public float a();
	
	/**
	 * *
	 */
	 float func_739();
	
	/**
	 * 
	 */
	public float b();
	
	/**
	 * *
	 */
	 java.lang.String func_737();
	
	/**
	 * 
	 */
	public java.lang.String c();

}
