// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class ThreadSleepForever extends java.lang.Thread{
	// FIELDS
	final net.minecraft.server.MienCrapftHurrvurr a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void run()

}
