// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class ThreadMonitorConnection extends java.lang.Thread{
	// FIELDS
	final NetworkManager a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void run()

}
