// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class TileEntityMobSpawner extends TileEntity {
	// FIELDS
	public int delay;
	public java.lang.String entityID;
	public double field_491;
	public double field_490;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_400_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_403_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_404_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_401_e();

}
