// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class TileEntity {
	// FIELDS
	public World worldObj;
	public int xCoord;
	public int yCoord;
	public int zCoord;
	private static java.util.Map nameToClassMap;
	private static java.util.Map classToNameMap;
	
	// METHODS
	
	/**
	 * Reads a tile entity from NBT.
	 */
	public abstract void readFromNBT(NBTTagCompound a);
	
	/**
	 * Writes a tile entity to NBT.
	 */
	public abstract void writeToNBT(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_91_d();
	
	/**
	 * Allows the entity to update its state. Overridden in most subclasses, e.g. the mob spawner uses this to count ticks and creates a new spawn inside its implementation.
	 */
	public abstract void updateEntity();
	
	/**
	 * *
	 */
	public abstract Packet func_20070();

}
