// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class TileEntitySign extends TileEntity {
	// FIELDS
	public java.lang.String[] signText;
	public int lineBeingEdited;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_870_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_869_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract Packet MIDDLECRAFT_func_871_f();

}
