// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class TileEntityMobSpawner extends TileEntity{
	// FIELDS
	public java.lang.String f;
	public double g;
	public int e;
	public double h;
	
	// METHODS
	
	/**
	 * 
	 */
	public void e()
	
	/**
	 * 
	 */
	public void b(NBTTagCompound a)
	
	/**
	 * 
	 */
	private void b()
	
	/**
	 * 
	 */
	public void a(NBTTagCompound a)
	
	/**
	 * 
	 */
	public boolean a()

}
