// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class TileEntityChest extends TileEntity {
	// FIELDS
	private ItemStack[] chestContents;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1544_a();
	
	/**
	 * 
	 */
	public abstract ItemStack MIDDLECRAFT_func_1545_a(int a);
	
	/**
	 * 
	 */
	public abstract ItemStack MIDDLECRAFT_func_1546_a(int a, int b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1547_a(int a, ItemStack b);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1549_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_1552_a_(EntityPlayer a);
	
	/**
	 * 
	 */
	public abstract java.lang.String MIDDLECRAFT_func_1548_b();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_1550_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract int MIDDLECRAFT_func_1551_c();

}
