// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class TileEntity {
	// FIELDS
	public World worldObj;
	public int xCoord;
	public int yCoord;
	public int zCoord;
	private static java.util.Map nameToClassMap;
	private static java.util.Map classToNameMap;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a(NBTTagCompound a);
	
	/**
	 * 
	 */
	private abstract static void a(java.lang.Class a, java.lang.String b);
	
	/**
	 * 
	 */
	public abstract void b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract static TileEntity c(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void d();
	
	/**
	 * 
	 */
	public abstract void e();
	
	/**
	 * 
	 */
	public abstract Packet f();

}
