// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class TileEntity {
	// FIELDS
	public World worldObj;
	public int xCoord;
	public int yCoord;
	public int zCoord;
	private static java.util.Map nameToClassMap;
	private static java.util.Map classToNameMap;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_209_a(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_210_b(NBTTagCompound a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_213_d();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_211_e();
	
	/**
	 * 
	 */
	public abstract Packet MIDDLECRAFT_func_214_f();

}
