// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Vec3D{
	// FIELDS
	private static java.util.List d;
	private static int e;
	public double b;
	public double c;
	public double a;
	
	// METHODS
	
	/**
	 * 
	 */
	public static Vec3D b(double a, double b, double c)
	
	/**
	 * 
	 */
	public static void a()
	
	/**
	 * 
	 */
	public java.lang.String toString()
	
	/**
	 * 
	 */
	public Vec3D a(Vec3D a, double b)
	
	/**
	 * 
	 */
	public double d(double a, double b, double c)
	
	/**
	 * 
	 */
	public Vec3D b(Vec3D a, double b)
	
	/**
	 * 
	 */
	public Vec3D c(double a, double b, double c)
	
	/**
	 * 
	 */
	public Vec3D c(Vec3D a, double b)
	
	/**
	 * 
	 */
	public double b(Vec3D a)
	
	/**
	 * 
	 */
	public double a(Vec3D a)
	
	/**
	 * 
	 */
	public Vec3D b()
	
	/**
	 * 
	 */
	public double c()
	
	/**
	 * 
	 */
	private Vec3D e(double a, double b, double c)
	
	/**
	 * 
	 */
	public static Vec3D a(double a, double b, double c)

}
