// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract interface interface Vec3D{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void a()
	
	/**
	 * 
	 */
	public abstract kx a(Packet17AddToInventory a, int b, int c)
	
	/**
	 * 
	 */
	public abstract void a(Packet17AddToInventory a, kx b)
	
	/**
	 * 
	 */
	public abstract void b()
	
	/**
	 * 
	 */
	public abstract void b(Packet17AddToInventory a, kx b)

}
