// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class Vec3D {
	// FIELDS
	public double xCoord;
	public double yCoord;
	public double zCoord;
	private static java.util.List vectorList;
	private static int nextVector;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_262_a(Vec3D a);
	
	/**
	 * 
	 */
	public abstract Vec3D MIDDLECRAFT_func_266_a(Vec3D a, double b);
	
	/**
	 * 
	 */
	public abstract Vec3D MIDDLECRAFT_func_260_b();
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_263_b(Vec3D a);
	
	/**
	 * 
	 */
	public abstract Vec3D MIDDLECRAFT_func_267_b(Vec3D a, double b);
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_265_c();
	
	/**
	 * 
	 */
	public abstract Vec3D MIDDLECRAFT_func_261_c(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract Vec3D MIDDLECRAFT_func_268_c(Vec3D a, double b);
	
	/**
	 * 
	 */
	public abstract double MIDDLECRAFT_func_264_d(double a, double b, double c);
	
	/**
	 * 
	 */
	public abstract java.lang.String MIDDLECRAFT_func_269_toString();

}
