// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class World extends ItemBlock{
	// FIELDS
	
	// METHODS
	
	/**
	 * *
	 */
	public boolean generate(Packet17AddToInventory a, java.util.Random b, int c, int d, int e)
	
	/**
	 * 
	 */
	private BlockSponge a(java.util.Random a)
	
	/**
	 * 
	 */
	private java.lang.String b(java.util.Random a)

}
