// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldGenHellLava extends WorldGenerator {
	// FIELDS
	private int field_4250;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_356_a(World a, java.util.Random b, int c, int d, int e);

}
