// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class World{
	// FIELDS
	private java.util.Set D;
	private long E;
	private long F;
	private IChunkProvider G;
	private java.util.List A;
	private java.util.List B;
	private java.util.TreeSet C;
	private int L;
	private java.util.List M;
	private NBTTagCompound H;
	private java.util.ArrayList I;
	private int J;
	private java.util.Set K;
	public int f;
	protected int g;
	public java.util.List d;
	public long e;
	public java.util.List b;
	public java.util.List c;
	public boolean a;
	public int n;
	public int o;
	public java.util.Random l;
	public int m;
	protected int j;
	public int k;
	protected int h;
	public boolean i;
	public final java.lang.String w;
	public long v;
	public long u;
	public java.io.File t;
	public java.io.File s;
	protected java.util.List r;
	public final WorldProvider q;
	public boolean p;
	public boolean z;
	static int y;
	public boolean x;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(java.util.List a)
	
	/**
	 * 
	 */
	public int a(float a)
	
	/**
	 * 
	 */
	public void b(java.util.List a)
	
	/**
	 * 
	 */
	public float a(Vec3D a, AxisAlignedBB b)
	
	/**
	 * 
	 */
	public void d(Entity a)
	
	/**
	 * 
	 */
	public boolean a(int a, int b, int c, int d, boolean e)
	
	/**
	 * 
	 */
	public void a(Entity a, java.lang.String b, float c, float d)
	
	/**
	 * 
	 */
	public void a(java.lang.String a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void b(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void g(int a, int b, int c)
	
	/**
	 * 
	 */
	public Explosion a(Entity a, double b, double c, double d, float e, boolean f)
	
	/**
	 * 
	 */
	public void e(Entity a)
	
	/**
	 * 
	 */
	public Chunk b(int a, int b)
	
	/**
	 * 
	 */
	public MovingObjectPosition a(Vec3D a, Vec3D b)
	
	/**
	 * 
	 */
	public boolean a(Entity a)
	
	/**
	 * 
	 */
	public boolean c(AxisAlignedBB a)
	
	/**
	 * 
	 */
	public int a(int a, int b)
	
	/**
	 * 
	 */
	public void a(IWorldAccess a)
	
	/**
	 * 
	 */
	public boolean j(int a, int b, int c)
	
	/**
	 * 
	 */
	public boolean a(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void f(Entity a)
	
	/**
	 * 
	 */
	public boolean d()
	
	/**
	 * 
	 */
	protected void e(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public byte[] c(int a, int b, int c, int d, int e, int f)
	
	/**
	 * 
	 */
	protected void scheduleBlockUpdate()
	
	/**
	 * 
	 */
	public java.util.List b(Entity a, AxisAlignedBB b)
	
	/**
	 * 
	 */
	public boolean b(int a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	private boolean f(int a, int b)
	
	/**
	 * 
	 */
	public void h()
	
	/**
	 * 
	 */
	private void i()
	
	/**
	 * 
	 */
	public int d(int a, int b)
	
	/**
	 * 
	 */
	public boolean j(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public int i(int a, int b, int c)
	
	/**
	 * 
	 */
	public boolean a(AxisAlignedBB a, Material b, Entity c)
	
	/**
	 * 
	 */
	public boolean o(int a, int b, int c)
	
	/**
	 * 
	 */
	public boolean f(int a, int b, int c)
	
	/**
	 * 
	 */
	public EntityPlayer a(double a, double b, double c, double d)
	
	/**
	 * 
	 */
	public boolean b()
	
	/**
	 * 
	 */
	public boolean d(int a, int b, int c)
	
	/**
	 * 
	 */
	public WorldChunkManager a()
	
	/**
	 * 
	 */
	public boolean d(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public MovingObjectPosition a(Vec3D a, Vec3D b, boolean c)
	
	/**
	 * 
	 */
	public boolean c(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean a(boolean a)
	
	/**
	 * 
	 */
	public Material c(int a, int b, int c)
	
	/**
	 * 
	 */
	private void k(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void a(double a, double b, double c, java.lang.String d, float e, float f)
	
	/**
	 * 
	 */
	public void a(boolean a, IProgressUpdate b)
	
	/**
	 * 
	 */
	public void a(EnumSkyBlock a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public void b(int a, int b, int c, TileEntity d)
	
	/**
	 * 
	 */
	public void f()
	
	/**
	 * 
	 */
	public int b(int a, int b, int c)
	
	/**
	 * 
	 */
	public TileEntity l(int a, int b, int c)
	
	/**
	 * 
	 */
	public void f(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public int e(int a, int b)
	
	/**
	 * 
	 */
	public float b(float a)
	
	/**
	 * 
	 */
	public EntityPlayer a(Entity a, double b)
	
	/**
	 * 
	 */
	public void b(EnumSkyBlock a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public int a(java.lang.Class a)
	
	/**
	 * 
	 */
	public void g(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void h(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public int a(EnumSkyBlock a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean a(int a, int b, int c, int d, int e, int f)
	
	/**
	 * 
	 */
	public void e()
	
	/**
	 * 
	 */
	public boolean e(int a, int b, int c)
	
	/**
	 * 
	 */
	public boolean a(AxisAlignedBB a, Material b)
	
	/**
	 * 
	 */
	public void a(EnumSkyBlock a, int b, int c, int d, int e, int f, int g, boolean h)
	
	/**
	 * 
	 */
	public PathEntity a(Entity a, Entity b, float c)
	
	/**
	 * 
	 */
	public float k(int a, int b, int c)
	
	/**
	 * 
	 */
	public boolean b(AxisAlignedBB a)
	
	/**
	 * 
	 */
	public int a(int a, int b, int c)
	
	/**
	 * 
	 */
	public void a(EnumSkyBlock a, int b, int c, int d, int e, int f, int g)
	
	/**
	 * 
	 */
	public java.util.List a(java.lang.Class a, AxisAlignedBB b)
	
	/**
	 * 
	 */
	public Chunk c(int a, int b)
	
	/**
	 * 
	 */
	public void a(int a, int b, int c, TileEntity d)
	
	/**
	 * 
	 */
	public boolean a(AxisAlignedBB a)
	
	/**
	 * 
	 */
	public void a(Entity a, boolean b)
	
	/**
	 * 
	 */
	public boolean n(int a, int b, int c)
	
	/**
	 * 
	 */
	protected void b(Entity a)
	
	/**
	 * 
	 */
	public boolean b(AxisAlignedBB a, Material b)
	
	/**
	 * 
	 */
	public void a(java.lang.String a, double b, double c, double d, double e, double f, double g)
	
	/**
	 * 
	 */
	public void b(int a, int b, int c, int d, int e, int f)
	
	/**
	 * 
	 */
	public boolean a(EntityPlayer a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void m(int a, int b, int c)
	
	/**
	 * 
	 */
	public Explosion a(Entity a, double b, double c, double d, float e)
	
	/**
	 * 
	 */
	protected IChunkProvider a(java.io.File a)
	
	/**
	 * 
	 */
	public void c()
	
	/**
	 * 
	 */
	protected void c(Entity a)
	
	/**
	 * 
	 */
	public boolean i(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public boolean h(int a, int b, int c)
	
	/**
	 * 
	 */
	public int a(int a, int b, int c, boolean d)
	
	/**
	 * 
	 */
	public PathEntity a(Entity a, int b, int c, int d, float e)
	
	/**
	 * 
	 */
	public java.util.List a(Entity a, AxisAlignedBB b)
	
	/**
	 * 
	 */
	public boolean a(int a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public void a(Entity a, byte b)

}
