// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldProvider {
	// FIELDS
	public World worldObj;
	public WorldChunkManager worldChunkMgr;
	public boolean field_6167;
	public boolean field_6166;
	public boolean field_4306;
	public float[] lightBrightnessTable;
	public int worldType;
	private float[] field_6164;
	
	// METHODS
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_777_a();
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_780_a(int a, int b);
	
	/**
	 * 
	 */
	public abstract float MIDDLECRAFT_func_781_a(long a, float b);
	
	/**
	 * *
	 */
	public abstract void registerWorld(World a);
	
	/**
	 * 
	 */
	public abstract IChunkLoader MIDDLECRAFT_func_779_a(java.io.File a);
	
	/**
	 * 
	 */
	protected abstract void MIDDLECRAFT_func_776_b();
	
	/**
	 * 
	 */
	public abstract IChunkProvider MIDDLECRAFT_func_778_c();

}
