// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldGenLiquids extends WorldGenerator {
	// FIELDS
	private int liquidBlockId;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean a(World a, java.util.Random b, int c, int d, int e);

}
