// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldChunkManager{
	// FIELDS
	private NoiseGeneratorOctaves2 f;
	private NoiseGeneratorOctaves2 g;
	public jq[] d;
	private NoiseGeneratorOctaves2 e;
	public double[] b;
	public double[] c;
	public double[] a;
	
	// METHODS
	
	/**
	 * 
	 */
	public jq[] a(jq[] a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public jq[] a(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public MobSpawnerBase a(int a, int b)
	
	/**
	 * 
	 */
	public double[] a(double[] a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public MobSpawnerBase a(ChunkCoordIntPair a)

}
