// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldChunkManagerHell extends WorldChunkManager{
	// FIELDS
	private double f;
	private double g;
	private MobSpawnerBase e;
	
	// METHODS
	
	/**
	 * 
	 */
	public jq[] a(jq[] a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public jq[] a(int a, int b, int c, int d)
	
	/**
	 * 
	 */
	public MobSpawnerBase a(int a, int b)
	
	/**
	 * 
	 */
	public double[] a(double[] a, int b, int c, int d, int e)
	
	/**
	 * 
	 */
	public MobSpawnerBase a(ChunkCoordIntPair a)

}
