// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldManager{
	// FIELDS
	private net.minecraft.server.MienCrapftHurrvurr a;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a(int a, int b, int c)
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	public void a(java.lang.String a, int b, int c, int d)
	
	/**
	 * 
	 */
	public void a(java.lang.String a, double b, double c, double d, double e, double f, double g)
	
	/**
	 * 
	 */
	public void a(java.lang.String a, double b, double c, double d, float e, float f)
	
	/**
	 * 
	 */
	public void a(Entity a)
	
	/**
	 * 
	 */
	public void a(int a, int b, int c, TileEntity d)
	
	/**
	 * 
	 */
	public void a(int a, int b, int c, int d, int e, int f)
	
	/**
	 * 
	 */
	public void b(Entity a)

}
