// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldChunkManager {
	// FIELDS
	public double[] temperature;
	public double[] humidity;
	public double[] field_4257;
	public MobSpawnerBase[] field_4256;
	private NoiseGeneratorOctaves2 field_4255;
	private NoiseGeneratorOctaves2 field_4254;
	private NoiseGeneratorOctaves2 field_4253;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract MobSpawnerBase MIDDLECRAFT_func_813_a(int a, int b);
	
	/**
	 * 
	 */
	public abstract MobSpawnerBase[] MIDDLECRAFT_func_814_a(int a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract MobSpawnerBase MIDDLECRAFT_func_812_a(ChunkCoordIntPair a);
	
	/**
	 * 
	 */
	public abstract double[] MIDDLECRAFT_func_815_a(double[] a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract MobSpawnerBase[] MIDDLECRAFT_func_816_a(MobSpawnerBase[] a, int b, int c, int d, int e);

}
