// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldGenerator extends EntityArrow{
	// FIELDS
	private BlockFurnace a;
	private int b;
	private int c;
	private int h;
	
	// METHODS
	
	/**
	 * 
	 */
	public void a()
	
	/**
	 * 
	 */
	public void a(BlockStairs a)
	
	/**
	 * 
	 */
	public boolean b(BlockLog a)

}
