// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldManager {
	// FIELDS
	private net.minecraft.server.MinecraftServer mcServer;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_408_a();
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_409_a(int a, int b, int c);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_407_a(int a, int b, int c, int d, int e, int f);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_411_a(int a, int b, int c, TileEntity d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_404_a(Entity a);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_403_a(java.lang.String a, double b, double c, double d, double e, double f, double g);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_406_a(java.lang.String a, double b, double c, double d, float e, float f);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_410_a(java.lang.String a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract void MIDDLECRAFT_func_405_b(Entity a);

}
