// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldGenFlowers extends WorldGenerator {
	// FIELDS
	private int plantBlockId;
	
	// METHODS
	
	/**
	 * *
	 */
	public abstract boolean generate(World a, java.util.Random b, int c, int d, int e);

}
