// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldChunkManagerHell extends WorldChunkManager {
	// FIELDS
	private MobSpawnerBase field_4262;
	private double field_4261;
	private double field_4260;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract MobSpawnerBase a(int a, int b);
	
	/**
	 * 
	 */
	public abstract MobSpawnerBase[] a(int a, int b, int c, int d);
	
	/**
	 * 
	 */
	public abstract MobSpawnerBase a(ChunkCoordIntPair a);
	
	/**
	 * 
	 */
	public abstract double[] a(double[] a, int b, int c, int d, int e);
	
	/**
	 * 
	 */
	public abstract MobSpawnerBase[] a(MobSpawnerBase[] a, int b, int c, int d, int e);

}
