// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldProviderHell extends WorldProvider{
	// FIELDS
	
	// METHODS
	
	/**
	 * *
	 */
	 float calculateCelestialAngle(long a, float b);
	
	/**
	 * 
	 */
	public void a();
	
	/**
	 * 
	 */
	public boolean a(int a, int b);
	
	/**
	 * 
	 */
	public float a(long a, float b);
	
	/**
	 * 
	 */
	public IChunkLoader a(java.io.File a);
	
	/**
	 * Creates the light to brightness table
	 */
	 void generateLightBrightnessTable();
	
	/**
	 * 
	 */
	protected void b();
	
	/**
	 * Returns the chunk provider back for the world provider
	 */
	 IChunkProvider getChunkProvider();
	
	/**
	 * 
	 */
	public IChunkProvider c();

}
