// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldGenDungeons extends WorldGenerator{
	// FIELDS
	
	// METHODS
	
	/**
	 * 
	 */
	public boolean a(World a, java.util.Random b, int c, int d, int e)
	
	/**
	 * 
	 */
	private java.lang.String b(java.util.Random a)
	
	/**
	 * 
	 */
	 void a(double a, double b, double c)
	
	/**
	 * 
	 */
	private ItemStack a(java.util.Random a)

}
