// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldGenBigTree extends WorldGenerator{
	// FIELDS
	 int f;
	 double g;
	 int[] d;
	 int e;
	 java.util.Random b;
	 World c;
	static final byte[] a;
	 int n;
	 int[][] o;
	 int l;
	 int m;
	 double j;
	 double k;
	 double h;
	 double i;
	
	// METHODS
	
	/**
	 * 
	 */
	 void a(int a, int b, int c)
	
	/**
	 * 
	 */
	 boolean e()
	
	/**
	 * 
	 */
	 void a()
	
	/**
	 * 
	 */
	 void a(int[] a, int[] b, int c)
	
	/**
	 * 
	 */
	 float b(int a)
	
	/**
	 * 
	 */
	 void c()
	
	/**
	 * 
	 */
	 void a(int a, int b, int c, float d, byte e, int f)
	
	/**
	 * 
	 */
	 void d()
	
	/**
	 * 
	 */
	public boolean a(World a, java.util.Random b, int c, int d, int e)
	
	/**
	 * 
	 */
	 int a(int[] a, int[] b)
	
	/**
	 * 
	 */
	 boolean c(int a)
	
	/**
	 * 
	 */
	public void a(double a, double b, double c)
	
	/**
	 * 
	 */
	 float a(int a)
	
	/**
	 * 
	 */
	 void b()

}
