// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

public abstract class WorldGenMinable extends WorldGenerator {
	// FIELDS
	private int minableBlockId;
	private int numberOfBlocks;
	
	// METHODS
	
	/**
	 * 
	 */
	public abstract boolean MIDDLECRAFT_func_423_a(World a, java.util.Random b, int c, int d, int e);

}
