// AUTOMATICALLY GENERATED BY MIDDLECRAFT
/* Allows plugins to access server functions without needing to link the actual server Jar. */
package net.minecraft.server;

abstract class WorldGenFire{
	// FIELDS
	final int a;
	 java.lang.Object b;
	 WorldGenFire c;
	final int d;
	
	// METHODS
	
	/**
	 * *
	 */
	public final int getHash()
	
	/**
	 * *
	 */
	public final java.lang.Object getValue()
	
	/**
	 * 
	 */
	public final boolean equals(java.lang.Object a)
	
	/**
	 * 
	 */
	public final int hashCode()
	
	/**
	 * 
	 */
	public final java.lang.String toString()

}
